// Generated from exact text that remained English when the Spanish locale was active.
// Keep brand names and product specifications unchanged when reviewing updates.
export const SpanishLegacyAnespaBeaute: Readonly<Record<string, string>> = Object.freeze({
  "SPA MINERAL ION WATER · ENAGIC®": "SPA DE AGUA IONIZADA CON MINERALES · ENAGIC®",
  "3-YEAR WARRANTY": "GARANTÍA DE 3 AÑOS",
  "3-Year Enagic Warranty": "Garantía Enagic de 3 años",
  "5 types of hyaluronic acid maintain soft, hydrated-looking skin.": "Cinco tipos de ácido hialurónico ayudan a mantener la piel suave y con aspecto hidratado.",
  "120nm technology glides smoothly for a clean, residue-free finish.": "La tecnología de 120 nm se desliza suavemente para lograr un acabado limpio y sin residuos.",
  "120nm Vesicle Complex & Mink Oil Composite for radiant glow.": "Complejo de vesículas de 120 nm y compuesto de aceite de visón para una luminosidad radiante.",
  "Anespa® DX Mineral Ion Water Spa | True Legacy": "Anespa® DX | Spa de agua ionizada con minerales | True Legacy",
  "Buy Now": "Comprar ahora",
  "Talk to Me": "Háblame",
  "MINERAL ION WATER SPA · ENAGIC®": "SPA MINERAL ION WATER · ENAGIC®",
  "Turn Your Shower": "Convierte tu ducha",
  "Into a Spa.": "En un spa.",
  "Inspired by Japan's legendary hot springs, Anespa® DX filters your tap water and infuses natural Hokkaido mineral ions — transforming your daily shower into a private onsen ritual.": "Inspirado en las legendarias fuentes termales de Japón, Anespa® DX filtra el agua del grifo e infunde iones minerales naturales de Hokkaido, transformando su ducha diaria en un ritual onsen privado.",
  "Discover the Journey": "Descubre el viaje",
  "Made in Japan · Enagic®": "Fabricado en Japón · Enagic®",
  "Dual Filtration · Hokkaido Mineral Ions · Massage Shower": "Doble filtración · Hokkaido Mineral iones · Ducha de masaje",
  "Scroll": "Desplazamiento",
  "See It In Action": "Verlo en acción",
  "The Anespa® DX Experience": "La experiencia Anespa® DX",
  "Watch how Anespa® DX transforms ordinary tap water into mineral-rich spa water — right in your home.": "Vea cómo Anespa® DX transforma el agua corriente en agua de spa rica en minerales, justo en su hogar.",
  "Made in Japan": "Hecho en Japón",
  "Hokkaido Mineral Ions": "Iones minerales de Hokkaido",
  "Dual-Stage Filtration": "Filtración de doble etapa",
  "Onsen-Inspired Technology": "Tecnología inspirada en Onsen",
  "The Anespa® Journey": "El viaje Anespa®",
  "Tap Water In.": "Agua del grifo adentro.",
  "Onsen Out.": "Onsen fuera.",
  "Four precise stages transform ordinary tap water into mineral-enriched spa water — every single day.": "Cuatro etapas precisas transforman el agua corriente corriente en agua de spa enriquecida con minerales, todos los días.",
  "TAP WATER IN": "ENTRADA DE AGUA DEL GRIFO",
  "CARBON FILTRATION": "FILTRACIÓN DE CARBONO",
  "MINERAL IONIZATION": "IONIZACIÓN MINERAL",
  "SPA EXPERIENCE": "EXPERIENCIA DE SPA",
  "Stage": "Etapa",
  "Ordinary Tap Water": "Agua corriente del grifo",
  "Standard municipal water enters the system — carrying chlorine, rust sediment, and the chemical residue of city pipe networks.": "El agua municipal estándar entra en el sistema, transportando cloro, sedimentos de óxido y el residuo químico de las redes de tuberías de la ciudad.",
  "Active Carbon Purification": "Purificación activa del carbono",
  "The external carbon filter removes chlorine, odor, rust, and pipe residue — delivering clean, odor-free water to the mineral stage.": "El filtro de carbono externo elimina el cloro, el olor, el óxido y los residuos de tuberías, entregando agua limpia y sin olor a la etapa mineral.",
  "Hokkaido Mineral Infusion": "Infusión mineral de Hokkaido",
  "Futamata Radium Tufa and Maifan mineral stones from Japan's most celebrated hot springs release natural mineral ions into the water.": "Futamata Radium Tufa y Maifan piedras minerales de las aguas termales más famosas de Japón liberan iones minerales naturales en el agua.",
  "Your Private Onsen": "Tu onsen privado",
  "Mineral-rich water flows through the massage shower head — gentle, fresh, and invigorating. Your bathroom becomes a Japanese hot spring.": "El agua rica en minerales fluye a través del cabezal de ducha de masaje: suave, fresca e invigorizante. Su baño se convierte en un manantial japonés.",
  "Mineral Ion Water Spa": "Agua mineral de iones Spa",
  "Hokkaido Tufa · Maifan Stones · Active Carbon": "Hokkaido Tufa · Piedras Maifan · Carbono activo",
  "SOURCED FROM NATURE": "FUENTE DE LA NATURALEZA",
  "Inspired by Japan's": "Inspirado en la",
  "Most Sacred Springs.": "Manantiales más sagrados.",
  "For over a century, Futamata in Hokkaido has been revered for its therapeutic radium hot springs. Anespa® DX harnesses the same mineral principles — bringing that ancient restorative ritual directly to your home shower.": "Durante más de un siglo, Futamata, en Hokkaido, ha sido venerado por sus aguas termales terapéuticas con radio. Anespa® DX aplica los mismos principios minerales y lleva ese antiguo ritual restaurador directamente a la ducha de tu hogar.",
  "The filtration cartridge incorporates mineral Tufa sourced directly from the renowned Futamata Radium Hot Spring in Hokkaido — one of Japan's most celebrated therapeutic springs.": "El cartucho de filtración incorpora minerales Tufa procedentes directamente de la famosa fuente de calor Futamata Radium en Hokkaido, uno de los manantiales terapéuticos más famosos de Japón.",
  "Maifan Mineral Stones": "Piedras minerales de Maifan",
  "Maifan Stone — a natural mineral-rich stone prized across East Asia — conditions water and releases beneficial mineral ions, the same way nature has for millennia.": "Maifan Stone —una piedra rica en minerales naturales apreciada en toda Asia oriental— condiciona el agua y libera iones minerales beneficiosos, del mismo modo que la naturaleza ha tenido durante milenios.",
  "Before minerals touch your water, an external carbon filter removes chlorine, rust sediment, and pipe odor — so only clean, purified water enters the mineral stage.": "Antes de que los minerales toquen el agua, un filtro de carbono externo elimina el cloro, el sedimento oxidado y el olor de las tuberías, por lo que solo entra en la etapa mineral agua limpia y purificada.",
  "OFFICIAL ENAGIC® SPECS": "ESPECIFICACIONES ENAGIC® OFICIALES",
  "Technical Excellence": "Excelencia técnica",
  "Built in Japan with premium materials and double-stage mineral conditioning.": "Construido en Japón con materiales premium y acondicionamiento mineral de doble etapa.",
  "Flow Rate": "Caudal",
  "Up to 10 liters/min of mineral spa water.": "Hasta 10 litros/min de agua mineral del balneario.",
  "External Filter": "Filtro externo",
  "Active Carbon": "Carbono activo",
  "Removes chlorine, rust, and pipe sediment.": "Elimina el cloro, el óxido y los sedimentos de tuberías.",
  "Mineral Cartridge": "Cartucho mineral",
  "Futamata Tufa & Maifan stone blend.": "Futamata Tufa & Maifán mezcla de piedra.",
  "Warranty": "Garantía",
  "ISO 13485 quality. Made in Japan.": "Calidad ISO 13485. Fabricado en Japón.",
  "Mineral-Ion Water": "Agua mineral-lónica",
  "Formulated specifically for relaxing bath or shower use — not for drinking.": "Formulado específicamente para el uso relajante de baño o ducha, no para beber.",
  "Natural pH Balance": "Equilibrio natural del pH",
  "Preserves natural water pH while filtering impurities and adding minerals.": "Preserva el pH natural del agua mientras filtra las impurezas y agrega minerales.",
  "Simple Installation": "Instalación sencilla",
  "Connects easily to standard bath faucets and shower arms. No plumber needed.": "Se conecta fácilmente a grifos de baño estándar y brazos de ducha. No se necesita fontanero.",
  "Backed by Enagic's official 3-year manufacturer warranty.": "Respaldado por la garantía oficial del fabricante de Enagic por 3 años.",
  "DX Enhanced Design": "Diseño mejorado DX",
  "Larger ceramic cartridge and redesigned base for effortless filter replacement.": "Cartucho de cerámica más grande y base rediseñada para sustitución de filtro sin esfuerzo.",
  "Massage Shower Head": "Cabezal de ducha de masaje",
  "Multiple adjustable settings for a soothing, customizable shower intensity.": "Múltiples ajustes ajustables para una intensidad de ducha relajante y personalizable.",
  "ELEVATE YOUR DAILY RITUAL": "Eleve su ritual diario",
  "Your Private Onsen.": "Tu onsen privado.",
  "Every Single Day.": "Todos los días.",
  "Experience the restorative power of mineral-filtered spa water every morning and evening. Connect with a True Legacy advisor to bring Anespa® DX to your home.": "Experimente el poder restaurador del agua del spa filtrada con minerales todas las mañanas y noches. Conéctese con un asesor de True Legacy para traer Anespa® DX a su hogar.",
  "Order Anespa® DX": "Comprar Anespa® DX",
  "True Legacy Duo": "True Legacy Duo",
  "True Legacy World": "True Legacy World",
  "True Legacy LATAM": "True Legacy LATAM",
  "True Legacy World.": "True Legacy World.",
  "Go back": "Regresa",
  "United States": "Estados Unidos",
  "Morocco": "Marruecos",
  "Brazil": "Brasil",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  "Malaysia": "Malasia",
  "Turkey": "Turquía",
  "Spain": "España",
  "European Union": "Unión Europea",
  "Legal": "Jurídico",
  "Back to top": "Volver al principio",
  "Kangen Beauté® | Three-Step Skincare Ritual | True Legacy": "Kangen Beauté® | Ritual de cuidado de la piel en tres pasos | True Legacy",
  "Ask About Ordering": "Pregunte sobre el pedido",
  "Ask": "Preguntar",
  "THE TIMELESS RADIANCE COLLECTION": "LA COLECCIÓN DE LA RADIANZA TIEMPO",
  "Return to Your Original": "Volver a su original",
  "Beauty": "Belleza",
  "Three Meticulously Crafted Steps. One Elevated Skincare Ritual.": "Tres pasos meticulosamente hechos.",
  "Kangen Beauté® is an exclusive Enagic skincare collection inspired by Kangen Water® and Okinawan Ukon, bringing together Japanese precision and Korean skincare artistry.": "Kangen Beauté® es una colección exclusiva de cuidado de la piel de Enagic, inspirada en Kangen Water® y Okinawan Ukon, que une la precisión japonesa con el arte coreano del cuidado de la piel.",
  "Kangen Beauté® Collection": "Colección Kangen Beauté®",
  "Discover the Three-Step Ritual": "Descubre el Ritual de Tres Pasos",
  "For external use only · Individual results may vary": "Sólo para uso externo · Los resultados individuales pueden variar",
  "pH 5.5 Formula": "Fórmula de pH 5.5",
  "Timeless Radiance Three-Step Ritual": "Radiancia atemporal Ritual de tres pasos",
  "First Light Essence · Vital Rich Cream · Crystal Ampoule Cream": "Primera esencia de luz · Crema rica vital · Crema de cristal",
  "Watch the Collection Story": "Vea la historia de la colección",
  "See the Three-Step Ritual in Motion": "Vea el Ritual de Tres Pasos en Movimiento",
  "After discovering the collection, watch how the Kangen Beauté® ritual comes together—then connect with": "Después de descubrir la colección, observe cómo se une el ritual de Kangen Beauté® y luego conecte con",
  "for availability and the official ordering path in your market.": "para la disponibilidad y la ruta oficial de pedidos en su mercado.",
  "Three-step skincare ritual": "ritual de cuidado de la piel de tres pasos",
  "Inspired by Kangen Water®": "Inspirado en Kangen Water®",
  "Features Okinawan Ukon": "Características Okinawan Ukon",
  "Exclusive to Enagic®": "Exclusivo de Enagic®",
  "Full ingredient transparency": "Transparencia completa del ingrediente",
  "THE KANGEN BEAUTÉ PHILOSOPHY": "LA FILOSOFIA DE KANGEN BEAUTE",
  "Where Water, Heritage and Skincare Artistry Meet": "Donde se encuentran el agua, el patrimonio y el cuidado de la piel",
  "Enagic Heritage": "El legado de Enagic",
  "Kangen Beauté is built around Kangen Water at pH 5.5 and formulated to help support the skin’s moisture barrier while delivering hydration-focused care.": "El Kangen Beauté está construido alrededor del agua de Kangen a pH 5,5 y formulado para ayudar a apoyar la barrera de humedad de la piel mientras proporciona un cuidado centrado en la hidratación.",
  "Japanese Precision": "Precisión japonesa",
  "The collection draws from Enagic’s Japanese heritage, water-ionization knowledge, and Okinawan Ukon story.": "La colección se inspira en el legado japonés de Enagic, su conocimiento sobre la ionización del agua y la historia de Okinawan Ukon.",
  "Korean Artistry": "Artística coreana",
  "Advanced skincare ingredients and a proprietary delivery approach create a layered ritual designed for hydration, nourishment, and a luminous-looking finish.": "Los ingredientes avanzados para el cuidado de la piel y un enfoque de entrega patentado crean un ritual en capas diseñado para la hidratación, nutrición y un acabado luminoso.",
  "The Three-Step Ritual": "El Ritual de Tres Pasos",
  "Each formula plays a different role. Use the complete collection as a layered ritual, following the official product directions.": "Cada fórmula juega un papel diferente. Utilice la colección completa como un ritual en capas, siguiendo las instrucciones oficiales del producto.",
  "STEP 1 · PREPARE + HYDRATE": "PASO 1 · PREPARACIÓN + HIDRATO",
  "First Light Essence": "Primera esencia de luz",
  "A multilayered essence designed to refresh the look of skin, support a smooth hydrated feel, and prepare the skin for the next step.": "Una esencia multicapa diseñada para refrescar el aspecto de la piel, apoyar una sensación hidratada suave, y preparar la piel para el siguiente paso.",
  "Helps support the look of a comfortable, balanced skin barrier.": "Ayuda a apoyar la apariencia de una barrera de piel cómoda y equilibrada.",
  "Milk-Derived Actives": "Activos Leche-Derived",
  "Milk Exosome Complex & Curcumin Composite to condition skin.": "Complejo de Exosomas de Leche y Curcumina Compuesto para acondicionar la piel.",
  "Prepare & Absorb": "Preparar y absorber",
  "Designed to blend the formula seamlessly into the skin surface.": "Diseñado para mezclar la fórmula sin problemas en la superficie de la piel.",
  "STEP 2 · NOURISH + RENEW": "PASO 2 · NORUÉS + RENOVACIÓN",
  "Vital Rich Cream": "Crema rica vital",
  "A rich treatment cream designed to help improve the appearance of firmness, smoothness, tone, and radiance as part of an evening skincare ritual.": "Una rica crema de tratamiento diseñada para ayudar a mejorar la apariencia de firmeza, suavidad, tono y luminosidad como parte de un ritual de cuidado de la piel vespertino.",
  "Skin Renewal (PDRN)": "Renovación de la piel (PDRN)",
  "PDRN + peptides help support smoother, firmer-looking skin.": "PDRN + péptidos ayudan a apoyar una piel más suave y de aspecto más firme.",
  "Brightening Support": "Soporte de brillo",
  "Niacinamide helps promote a more even, radiant appearance.": "La niacinamida ayuda a promover una apariencia más uniforme y radiante.",
  "Deep Infusion": "Infusión profunda",
  "Formulated to channel active ingredients deep into the skin.": "Formulado para canalizar los ingredientes activos profundamente en la piel.",
  "Nature & Innovation": "Naturaleza e innovación",
  "Harmony of PDRN, Niacinamide, and Okinawan Ukon curcumin.": "Armonía de PDRN, Niacinamida y Okinawan Ukon curcumin.",
  "STEP 3 · PROTECT + REVITALIZE": "PASO 3 · PROTEGER + REVITAR",
  "Crystal Ampoule Cream": "Crema Ampoule de Cristal",
  "The final seal in the ritual. A concentrated cream designed to help lock in moisture and leave skin with a luminous, silky finish.": "El sello final en el ritual. Una crema concentrada diseñada para ayudar a bloquear la humedad y dejar la piel con un acabado luminoso y sedoso.",
  "Deep Nourishment": "Alimentación profunda",
  "Omega-7 + essential fatty acids enhance soft & smooth skin.": "Omega-7 + ácidos grasos esenciales mejoran la piel suave y suave.",
  "Barrier Support": "Apoyo a la barrera",
  "Ceramide-like lipids support moisture & strengthen skin barrier.": "Los lípidos de tipo ceramida apoyan la humedad y fortalecen la barrera cutánea.",
  "Silk Rich Finish": "Acabado rico en seda",
  "DAILY APPLICATION": "SOLICITUD DIARIA",
  "Build the Ritual Into Your Routine": "Construya el Ritual en su rutina",
  "MORNING ROUTINE": "MAÑANA RUTINA",
  "Begin with clean, dry skin.": "Comience con la piel limpia y seca.",
  "Apply First Light Essence according to the package directions.": "Aplicar First Light Essence según las instrucciones del paquete.",
  "Follow with the appropriate Beauté cream if directed for morning use.": "Siga con la crema de Beauté apropiada si está indicado para uso matutino.",
  "Complete the routine with a suitable broad-spectrum sunscreen from your existing skincare routine.": "Completa la rutina con un protector solar de amplio espectro adecuado de tu rutina de cuidado de la piel existente.",
  "EVENING RITUAL": "RITUAL",
  "Cleanse and dry the skin.": "Limpiar y secar la piel.",
  "Apply First Light Essence.": "Aplicar Primera Esencia de Luz.",
  "Follow with Vital Rich Cream.": "Siga con Vital Rich Cream.",
  "Complete the ritual with Crystal Ampoule Cream when directed.": "Completar el ritual con Crystal Ampoule Cream cuando esté dirigido.",
  "FORMULATION HIGHLIGHTS": "DESTACA LA FORMULACIÓN",
  "Advanced Ingredients in Harmony": "Ingredientes avanzados en armonía",
  "Kangen Water at pH 5.5": "Agua de Kangen a pH 5,5",
  "Used to help support a balanced, hydrated feel.": "Se utiliza para ayudar a soportar una sensación equilibrada e hidratada.",
  "Turmeric-inspired care connected to Enagic’s Okinawan heritage.": "Cuidados de inspiración cúrcuma relacionados con el patrimonio enágico de Okinawan.",
  "Multiple forms of hyaluronic acid for layered hydration.": "Múltiples formas de ácido hialurónico para la hidratación en capas.",
  "Niacinamide": "Niacinamida",
  "Included to support a brighter and more even-looking complexion.": "Incluido para soportar una tez más brillante y más uniforme.",
  "Peptide Complex": "Complejo Peptide",
  "A multi-peptide system included within the disclosed formulas.": "Un sistema multipéptido incluido en las fórmulas reveladas.",
  "PDRN & Sodium DNA": "PDRN y ADN sódico",
  "Featured within the Vital Rich Cream ingredient story.": "Destacado dentro de la historia de ingredientes Vital Rich Cream.",
  "Collagen & Elastin": "Colágeno y Elastin",
  "Included as cosmetic-conditioning ingredients.": "Incluido como ingredientes de acondicionamiento cosmético.",
  "Botanical Extracts": "Extractos botánicos",
  "Includes Centella asiatica, green tea, camellia, grapefruit, oat, and ginseng.": "Incluye Centella asiatica, té verde, camelia, pomelo, avena y ginseng.",
  "FULL INGREDIENT DISCLOSURE": "DIVULGACIÓN PÚBLICA",
  "Luxury Includes Knowing What Is Inside": "El lujo incluye saber lo que hay dentro",
  "Review the complete ingredient list before applying any product, especially if you have known sensitivities or ethical ingredient preferences.": "Revise la lista completa de ingredientes antes de aplicar cualquier producto, especialmente si ha conocido sensitividades o preferencias éticas de ingredientes.",
  "First Light Essence: Full INCI List": "Primera luz Essence: Lista completa de INCI",
  "Vital Rich Cream: Full INCI List": "Crema rica vital: Lista completa de INCI",
  "Crystal Ampoule Cream: Full INCI List": "Crema de cristal Ampoule: Lista completa de INCI",
  "Important Transparency Disclosure:": "Información importante sobre la transparencia:",
  "Disclosed ingredients include fragrance allergens (limonene, linalool, hexyl cinnamal), milk/whey proteins, salmon testis exosomes, collagen, beeswax, and mink oil. This collection is not labeled vegan or hypoallergenic.": "Los ingredientes divulgados incluyen alérgenos de fragancia (limoneno, linalool, hexil cinnamal), proteínas de leche/whey, exosomas de salmón testículos, colágeno, cera de abejas y aceite de mink. Esta colección no está etiquetada como vegana o hipoalergénica.",
  "Is Kangen Beauté Right for Your Ritual?": "¿Es Kangen Beauté adecuado para su Ritual?",
  "People seeking layered hydration and moisture barrier support": "Personas que buscan soporte de barrera de humedad y hidratación en capas",
  "People interested in a richer evening skincare ritual": "Personas interesadas en un ritual de cuidado de la piel más rico",
  "People wanting to improve the appearance of smoothness and radiance": "Personas que quieren mejorar la apariencia de suavidad y luminosidad",
  "Existing Enagic customers exploring the Kangen lifestyle beyond water": "Clientes actuales de Enagic que exploran el estilo de vida Kangen más allá del agua",
  "Start With Care": "Comience con el cuidado",
  "For external use only. Read complete ingredient lists before use.": "Sólo para uso externo. Lea las listas completas de ingredientes antes de usar.",
  "Patch test each product on a small area of skin before applying broadly.": "El parche prueba cada producto en un área pequeña de la piel antes de aplicar ampliamente.",
  "Introduce one new product at a time if you have sensitive skin.": "Introduce un producto nuevo a la vez si tienes piel sensible.",
  "Avoid direct contact with eyes. Discontinue use if irritation occurs.": "Evite el contacto directo con los ojos.",
  "EXCLUSIVE TO ENAGIC": "EXCLUSIVA A LA ENÁGICA",
  "A New Expression of the Kangen Lifestyle": "Una nueva expresión del estilo de vida de Kangen",
  "Kangen Beauté extends Enagic’s water-centered heritage into a three-step skincare collection created exclusively for the company.": "Kangen Beauté amplía el legado de Enagic centrado en el agua mediante una colección de cuidado de la piel en tres pasos creada exclusivamente para la compañía.",
  "View Official Kangen Beauté Information": "Ver la información oficial de Kangen Beauté",
  "Questions About Kangen Beauté": "Preguntas sobre Kangen Beauté",
  "What products are included?": "¿Qué productos están incluidos?",
  "What order should I use them?": "¿Qué orden debo usar?",
  "Is Kangen Beauté made with Kangen Water?": "¿Está Kangen Beauté hecho con Kangen Water?",
  "Does the collection contain turmeric?": "¿La colección contiene cúrcuma?",
  "Is it fragrance-free?": "¿Está libre de fragancias?",
  "Is Kangen Beauté vegan?": "¿Es Kangen Beauté vegano?",
  "Is it suitable for sensitive skin?": "¿Es adecuado para pieles sensibles?",
  "Does it remove wrinkles or reverse aging?": "¿Quita las arrugas o invierte el envejecimiento?",
  "Can it treat acne, eczema, rosacea, or another skin condition?": "¿Puede tratar acné, eczema, rosacea, u otra condición de la piel?",
  "Where is the collection available?": "¿Dónde está disponible la colección?",
  "How can I purchase it?": "¿Cómo puedo comprarlo?",
  "YOUR PERSONAL BEAUTÉ GUIDE": "TU GUÍA PERSONAL DE BEAUTÉ",
  "Explore the Ritual With": "Explore el Ritual con",
  "Leader can help you understand the three-step Kangen Beauté ritual, confirm availability, and guide you through the official purchasing options in your market.": "El líder puede ayudarle a entender el ritual de tres pasos de Kangen Beauté, confirmar la disponibilidad y guiarlo a través de las opciones de compra oficiales en su mercado.",
  "About Kangen Beauté": "Acerca de Kangen Beauté",
  "View": "Ver",
  "’s Profile": "Perfil",
  "BEGIN YOUR RITUAL": "INICIA TU RITUAL",
  "Ready to Explore Kangen Beauté?": "¿Listo para explorar Kangen Beauté?",
  "Discover the complete three-step collection and ask your verified distributor about availability, pricing, and official purchasing options in your market.": "Descubra la colección completa de tres pasos y pregunte a su distribuidor verificado sobre disponibilidad, precios y opciones oficiales de compra en su mercado.",
  "Message": "Mensaje",
  "Request Beauté Information": "Solicitar información sobre Beauté",
  "Premium skincare. Complete transparency. Personal guidance.": "Premium skincare. Completa transparencia. Orientación personal.",
  "Kangen Beauté is a cosmetic skincare collection for external use only. It is not intended to diagnose, treat, cure, or prevent any medical condition. Cosmetic results vary by individual. Review the complete ingredient lists, patch test before broader use, and discontinue use if irritation occurs. Product formulation, packaging, availability, and permitted claims may vary by country.": "Kangen Beauté es una colección cosmética para el cuidado de la piel de uso exclusivamente externo. No pretende diagnosticar, tratar, curar ni prevenir ninguna afección médica. Los resultados cosméticos varían según cada persona. Revisa las listas completas de ingredientes, realiza una prueba en una zona pequeña antes de un uso más amplio y suspende su uso si se produce irritación. La formulación, el empaque, la disponibilidad y las afirmaciones permitidas del producto pueden variar según el país.",
  "Return to Leader's profile": "Volver al perfil de Leader",
  "Shared by Leader": "Compartido por Leader",
  "Discover the Kangen Beauté three-step skincare collection": "Descubre la colección de skincare de tres pasos de Kangen Beauté"
})
