// Generated from exact text that remained English when the Spanish locale was active.
// Keep brand names and product specifications unchanged when reviewing updates.
export const SpanishLegacyWagyuJr4: Readonly<Record<string, string>> = Object.freeze({
  "4 Solid Plates · 120W Low Energy": "4 placas sólidas · Bajo consumo de 120 W",
  "5 Functional Water Types": "5 tipos de agua funcional",
  "5 WATER TYPES": "5 TIPOS DE AGUA",
  "TAP WATER": "AGUA DEL GRIFO",
  "✕ NOT FOR DRINKING": "✕ NO APTA PARA BEBER",
  "4 solid platinum-titanium plates split water": "4 placas sólidas de platino y titanio separan el agua",
  "5 Water Types": "5 tipos de agua",
  "3 Years": "3 años",
  "4 solid plates": "4 placas sólidas",
  "3 Years Manufacturer Warranty": "3 años de garantía del fabricante",
  "5 distinct types": "5 tipos distintos",
  "Overview": "Sinopsis",
  "Video Demo": "Demostración de vídeo",
  "The Difference": "La diferencia",
  "Heritage": "Patrimonio",
  "The Ranch": "La Ranch",
  "Experience": "Experiencia",
  "The Sets": "Los conjuntos",
  "EN": "ES",
  "Independent Enagic Distributor": "Distribuidor Enágico Independiente",
  "Watch Video Demo": "Ver vídeo Demo",
  "Masami Ranch · F1 Crossbreed": "Ranch Masami · F1 Cruzado",
  "OFFICIAL VIDEO DEMONSTRATION": "DEMONSTRACIÓN OFICIAL DE VIDEO",
  "SEE HOW IT'S RAISED.": "Mira cómo se levanta.",
  "THE KANGEN WAGYU® EXPERIENCE.": "La experiencia Kangen Wagyu®.",
  "Discover the daily care, heritage genetics, and daily Kangen Water® hydration protocol at Masami Ranch that create exceptional marbling and unforgettable tenderness.": "Descubra el cuidado diario, la genética del patrimonio y el protocolo de hidratación diario Kangen Water® en Masami Ranch que crean un mármol excepcional y una ternura inolvidable.",
  "Official True Legacy Production · Masami Ranch, California": "Producción oficial de verdadero legado · Masami Ranch, California",
  "ABOUT ORDERING": "SOBRE LA ORDENACIÓN",
  "NO ADDED HORMONES": "NINGUNA REDES DE HORMA AÑADIDA",
  "NO ANTIBIOTICS": "NO ANTIBIÓTICA",
  "NO ANIMAL BYPRODUCTS": "No hay ningún producto animal",
  "KANGEN WATER® HYDRATED": "HIDRATADO CON KANGEN WATER®",
  "SHIPS FROZEN": "BUQUES FROZEN",
  "THE KANGEN DIFFERENCE": "LA DIFERENCIA DE KANGEN",
  "WATER FIRST.": "Primero el invierno.",
  "THEN EVERYTHING ELSE.": "Entonces todo lo demás.",
  "Marbling is the visible finish. What creates it is a deliberate series of uncompromised decisions made every single day at the ranch—beginning with what the cattle drink.": "Marbling es el final visible. Lo que lo crea es una serie deliberada de decisiones sin compromisos tomadas todos los días en el rancho, comenzando con lo que bebe el ganado.",
  "Daily Hydration Routine": "Rutina diaria de hidratación",
  "Enagic documents that the cattle at Masami Ranch are hydrated daily with electrolyzed-reduced Kangen Water® as a foundational element of their care.": "Enagic documenta que el ganado de Masami Ranch se hidrata diariamente con Kangen Water® reducida por electrólisis como elemento fundamental de su cuidado.",
  "Every animal drinks the same electrolyzed-reduced water Enagic has championed since 1974. It is the defining practice that sets Kangen Wagyu apart and contributes to exceptional animal well-being.": "Cada animal bebe el mismo agua electrolizada reducida Enágica ha defendido desde 1974. Es la práctica definitoria que distingue a Kangen Wagyu y contribuye al bienestar excepcional de los animales.",
  "Pure Integrity Standard": "Norma de integridad pura",
  "NOTHING ADDED": "NADA AÑADIDO",
  "No added hormones, no antibiotics, no chemical growth promotants, and zero animal byproducts. The cattle thrive on a wholesome vegetarian diet, pasture grass-fed and meticulously grain-finished.": "No hay hormonas añadidas, ni antibióticos, ni estimulantes del crecimiento químico, ni ningún subproducto animal. El ganado prospera con una dieta vegetariana sana, alimentado con pasto y meticulosamente acabado con granos.",
  "Northern California Pasture": "Pastura del norte de California",
  "MASAMI RANCH · 6,500 ACRES": "MASAMI RANCH · 6.500 ACRES",
  "Located in Corning in Northern California, Masami Ranch provides open pastures, clean air, and thoughtful low-stress husbandry. Serene surroundings directly reflect in tenderness on your plate.": "Situado en Corning en el norte de California, Masami Ranch ofrece pastos abiertos, aire limpio, y pensativo de baja tensión de la cría.",
  "Certified Cold-Chain Shipping": "Envío certificado en frío",
  "FROZEN FROM RANCH TO DOOR": "FRONZA DE RAZÓN A PUERTA",
  "Each cut is vacuum-sealed at the peak of freshness and delivered directly to your door using specialized cold-chain thermal packaging, guaranteeing that what is packed is what you savor.": "Cada corte se sella al vacío en el pico de frescura y se entrega directamente a su puerta mediante un embalaje térmico especializado en cadena fría, garantizando que lo que está envasado es lo que saborea.",
  "WAGYU LINEAGE": "LÍNEA DE WAGYU",
  "JAPANESE HERITAGE.": "Japonese Heritage.",
  "Kangen Wagyu is bred from a deliberate 50/50 cross between 100% fullblood Japanese Kuroge Wagyu (Black Wagyu) and high-quality American Black Angus.": "Kangen Wagyu es criado a partir de un cruce deliberado de 50/50 entre el 100% de sangre completa japonés Kuroge Wagyu (Wagyu Negro) y la alta calidad americana Negro Angus.",
  "Japan's most prized genetic line, renowned worldwide for its intricate web of intramuscular marbling, low-melting-point unsaturated fats, and melt-in-the-mouth tenderness.": "La línea genética más preciada de Japón, reconocida mundialmente por su intrincada red de martilleo intramuscular, grasas insaturadas de bajo punto de fusión y ternura en la boca.",
  "High-Quality Black Angus": "Angus negro de alta calidad",
  "The benchmark American breed, selected for robust muscle density, natural climate resilience, and the deep, savory beef flavor celebrated in top American steakhouses.": "La raza americana de referencia, seleccionada para la densidad muscular robusta, la resistencia al clima natural, y el sabor profundo y sabroso de la carne celebrada en los mejores asadores americanos.",
  "Result: F1 American Wagyu marrying Japanese silkiness with American substance.": "Resultado: F1 American Wagyu casando la sedosidad japonesa con la sustancia americana.",
  "The herd at Masami Ranch in Corning, California.": "La manada de Masami Ranch en Corning, California.",
  "Intricate intramuscular marbling characteristic of Kangen Wagyu beef cuts.": "Introducir jaspeo intramuscular característico de los cortes de carne de Kangen Wagyu.",
  "WHERE IT STARTS.": "Donde empieza.",
  "Nestled against the foothills of the Northern Sacramento Valley, Masami Ranch spans 6,500 acres of protected pastureland.": "Ubicado contra las estribaciones del Valle del Norte de Sacramento, Masami Ranch abarca 6.500 acres de pastizales protegidos.",
  "The herd thrives in a quiet, low-stress environment. Ample grazing acreage, fresh air, clean vegetarian nutrition, and daily Kangen Water® hydration form a deliberate husbandry cycle designed around quality rather than volume.": "El rebaño prospera en un ambiente tranquilo y de bajo estrés. Amplias áreas de pastoreo, aire fresco, nutrición vegetariana limpia y hidratación diaria Kangen Water® forman un ciclo de cría deliberado diseñado en torno a la calidad en lugar de volumen.",
  "Corning, California · Northern Sacramento Valley": "Corning, California · Valle del Norte de Sacramento",
  "THE CULINARY ART": "EL ARTE CULINARIO",
  "FROM THE RANCH TO YOUR TABLE.": "Del rancho a tu mesa.",
  "A sensory journey from pasture to searing skillet. Rich aroma, velvety mouthfeel, and deep caramelized crust.": "Un viaje sensorial desde el pasto hasta la sartén abrasadora. Aroma rico, sensación aterciopelada y corteza profunda caramelizada.",
  "Cast Iron Searing & Crust": "Hierro fundido Secado y Crust",
  "Because the intramuscular fat in Kangen Wagyu has a notably low melting point, high direct heat in cast iron creates a deep golden crust while keeping the interior juicy and tender.": "Debido a que la grasa intramuscular en Kangen Wagyu tiene un punto de fusión notablemente bajo, el alto calor directo en hierro fundido crea una profunda corteza dorada manteniendo el interior jugoso y tierno.",
  "Refined Dining at Home": "Comida refinada en casa",
  "Every cut delivers a balance of rich beef flavor and gentle umami that transforms an evening into an extraordinary culinary memory.": "Cada corte ofrece un balance de rico sabor a carne y umami suave que transforma una noche en una memoria culinaria extraordinaria.",
  "Exceptional Marbling": "Marbling excepcional",
  "Delicate webs of intramuscular fat melt at human body temperature for effortless tenderness.": "Delicadas redes de grasa intramuscular se funden a temperatura corporal humana para una sensibilidad sin esfuerzo.",
  "Velvety Texture": "Textura de terciopelo",
  "Slices effortlessly and dissolves gently on the palate without chewy resistance.": "Rebana sin esfuerzo y se disuelve suavemente en el paladar sin resistencia a masticar.",
  "Rich, Buttery Flavor": "Rico, Sabor de Culos",
  "Savory, deep, and satisfying umami that leaves a clean, pleasant finish.": "Sabroso, profundo y satisfactorio umami que deja un acabado limpio y agradable.",
  "Frozen Delivery": "Entrega congelada",
  "Individually vacuum-sealed at the source and packed with cold-chain dry ice.": "Sellado individualmente al vacío en la fuente y lleno de hielo seco de cadena fría.",
  "CURATED SELECTION": "SELECCIÓN CURSADA",
  "THE KANGEN WAGYU PREMIUM EXPERIENCE": "LA EXPERIENCIA DE CAMBIO DE KAGYU",
  "Product sets, availability, and reorder eligibility can change. Current offerings are confirmed through your distributor's official Enagic portal.": "Los conjuntos de productos, la disponibilidad y la elegibilidad para reordenar pueden cambiar. Las ofertas actuales se confirman a través del portal oficial Enágico de su distribuidor.",
  "SKU 2115 · FIRST ORDER": "SKU 2115 · PRIMER PEDIDO",
  "Premium Set: First Order": "Set Premium: primer pedido",
  "Comprehensive 29-Piece Culinary Box": "Caja de cocina integral 29-Piece",
  "Vacuum-sealed & cold-chain shipped": "Sellado por vacío y cadena en frío",
  "REORDER PROGRAM": "PROGRAMA DE REORDACIÓN",
  "Premium Set: Reorder": "Set Premium: Reordenar",
  "Exclusive For Returning Customers": "Exclusivo para devolver clientes",
  "A dedicated recurring reorder option available to registered customers through official Enagic accounts, keeping your freezer stocked with artisanal cuts.": "Una opción de reordenado recurrente dedicada a clientes registrados a través de cuentas Enágicas oficiales, manteniendo su congelador lleno de cortes artesanales.",
  "Artisan Packaged Savory Blend": "Mezcla de sabores artesanales",
  "Kangen Wagyu & Angus savory recipe": "Kangen Wagyu & Angus receta sabrosa",
  "Convenient for travel, gifting & snacking": "Conveniente para viajes, regalos y snacks",
  "Official Insulated Thermal Delivery": "Entrega térmica aislada oficial",
  "Orders ship frozen in customized Enagic Kangen Cattle containers engineered for temperature retention from ranch arrival to your table.": "Pedidos enviados congelados en contenedores Enágicos Kangen Cattle personalizados diseñados para la retención de temperatura desde la llegada del rancho a su mesa.",
  "True Legacy Global": "Verdadero legado mundial",
  "PERSONAL ASSISTANCE": "ASISTENCIA PERSONAL",
  "CURIOUS ABOUT KANGEN WAGYU?": "¿Curioso por Kangen Wagyu?",
  "Questions about availability, ordering or which option is right for you?": "Preguntas sobre la disponibilidad, el pedido o qué opción es adecuada para usted?",
  "\"I shared Kangen Wagyu with you because it demonstrates the extraordinary scope of the Enagic philosophy. Beyond our medical-grade water ionizers, this represents agricultural excellence, pure hydration, and artisanal dining. I'm here to help you verify current batch availability, check delivery eligibility, and ensure you place an authorized order.\"": "\"Compartí con ustedes a Kangen Wagyu porque demuestra el extraordinario alcance de la filosofía Enágica. Más allá de nuestros ionizadores de agua de grado médico, esto representa excelencia agrícola, hidratación pura y comida artesanal. Estoy aquí para ayudarle a verificar la disponibilidad actual por lotes, comprobar la elegibilidad de entrega y asegurarse de que usted coloca un pedido autorizado\".",
  "Send Message": "Enviar mensaje",
  "FREQUENTLY ASKED QUESTIONS": "PREGUNTAS FRECUENTES",
  "Questions About Kangen Wagyu": "Preguntas sobre Kangen Wagyu",
  "Clear, transparent answers about the breed, ranching practices, and ordering.": "Respuestas claras y transparentes sobre la raza, prácticas de rancho y pedidos.",
  "What is Kangen Wagyu?": "¿Qué es Kangen Wagyu?",
  "Kangen Wagyu® is a premium culinary program from Enagic featuring artisanal American Wagyu beef raised at Masami Ranch in Corning, California. It brings together historic Japanese Kuroge Wagyu genetics, premium American Black Angus, and daily hydration with Kangen Water®.": "Kangen Wagyu® es un programa culinario de primera calidad de Enágico con carne de vacuno Wagyu americana artesanal criada en Masami Ranch en Corning, California. Reúne genética histórica japonesa de Kuroge Wagyu, Angus negro americano premium e hidratación diaria con Kangen Water®.",
  "Where is it raised?": "¿Dónde se crió?",
  "What breed is Kangen Wagyu?": "¿Qué raza es Kangen Wagyu?",
  "What makes it different?": "¿Qué lo hace diferente?",
  "Is it hydrated with Kangen Water?": "¿Está hidratado con agua Kangen?",
  "Are hormones added?": "¿Se añaden hormonas?",
  "Are antibiotics used?": "¿Se usan antibióticos?",
  "How is it shipped?": "¿Cómo se envía?",
  "How do I order?": "¿Cómo ordeno?",
  "Is it available in my country?": "¿Está disponible en mi país?",
  "CULINARY EXCELLENCE": "EXCELENCIA CULINARIA",
  "TASTE WHAT": "TASTE QUÉ",
  "DIFFERENT LOOKS LIKE.": "Diferente parece.",
  "Discover Kangen Wagyu and speak directly with your True Legacy distributor about current batch availability and doorstep cold-chain delivery.": "Descubra Kangen Wagyu y hable directamente con su distribuidor True Legacy sobre la disponibilidad actual de lotes y la entrega en cadena de frío.",
  "Authentic American Wagyu · Raised at Masami Ranch · Delivered in supported U.S. markets": "Authentic American Wagyu · Retirada en Masami Ranch · Entregada en mercados estadounidenses apoyados",
  "Official Food, Shipping & Regulatory Disclosure:": "Divulgación oficial de alimentos, envíos y reglamentos:",
  "Kangen Wagyu® is a perishable food product raised at Masami Ranch in Corning, California. Product contents, pricing, packaging, inventory, and delivery timing are managed under official Enagic policies and are subject to change. Review official product labels, allergen information, and thawing directions upon delivery. Kangen Water® hydration is part of Enagic’s documented ranching practices and is not intended to diagnose, treat, cure, or guarantee specific health or nutritional outcomes.": "Kangen Wagyu® es un alimento perecedero criado en Masami Ranch, en Corning, California. El contenido, los precios, el empaque, el inventario y los plazos de entrega se gestionan conforme a las políticas oficiales de Enagic y están sujetos a cambios. Al recibir el producto, revisa las etiquetas oficiales, la información sobre alérgenos y las instrucciones de descongelación. La hidratación con Kangen Water® forma parte de las prácticas ganaderas documentadas de Enagic y no pretende diagnosticar, tratar ni curar enfermedades, ni garantizar resultados específicos de salud o nutrición.",
  "True Legacy Duo": "Duo verdadero legado",
  "True Legacy World": "El verdadero mundo del legado",
  "True Legacy LATAM": "El verdadero legado LATAM",
  "True Legacy World.": "Verdadero Mundo Legado.",
  "Return to Leader Profile": "Volver al perfil de Leader",
  "Shared by Mehdi Cohen": "Compartido por Mehdi Cohen",
  "Kangen Wagyu: The Wagyu Beef Raised With Kangen Water": "Kangen Wagyu: La carne de vacuno Wagyu se cría con agua de Kangen",
  "United States": "Estados Unidos",
  "Morocco": "Marruecos",
  "Brazil": "Brasil",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  "Malaysia": "Malasia",
  "Turkey": "Turquía",
  "Spain": "España",
  "European Union": "Unión Europea",
  "Legal": "Jurídico",
  "Back to top": "Volver al principio",
  "LeveLuk JrIV | Compact Kangen Water® System | True Legacy": "LeveLuk JrIV | Sistema compacto Kangen Water® | True Legacy",
  "Ask": "Preguntar",
  "Explore the JrIV": "Explore el JrIV",
  "Made in Japan · Enagic®": "Hecho en Japón · Enágico®",
  "Continuous electrolysis with touch-button selection and automated cleaning.": "Electrolisis continua con selección de botones táctiles y limpieza automatizada.",
  "pH 2.5 — 11.5": "pH 2,5 - 11,5",
  "Singles & Couples": "Singles & Parejas",
  "Scroll": "Desplazamiento",
  "LOWER ENERGY CONSUMPTION": "CONSUMO DE ENERGIA BAJA",
  "DESIGNED FOR SINGLES & COUPLES": "DESIGNADO PARA SINGLES Y PARQUES",
  "THE JUNIOR MODEL": "EL MODELO JUNIOR",
  "NOT EVERY HOME": "NO TODOS LOS HOGARES",
  "NEEDS THE K8.": "Necesita el K8.",
  "Some households need the greater output and eight-plate performance of the flagship K8. Others simply want the Kangen Water® experience in a machine designed around a smaller household.": "Algunos hogares necesitan la mayor producción y el rendimiento de ocho placas del buque insignia K8. Otros simplemente quieren la experiencia Kangen Water® en una máquina diseñada alrededor de un hogar más pequeño.",
  "That's where the JrIV fits.": "Ahí es donde encaja el JrIV.",
  "The right machine for the right home.": "La máquina adecuada para el hogar adecuado.",
  "FOR SINGLES": "PARA LOS SINGLES",
  "FOR COUPLES": "Para parejas",
  "LOWER DEMAND": "DEMANDA BAJA",
  "See If JrIV Fits My Home": "Vea si JrIV encaja en mi hogar",
  "HEALTHY LIVING · STREAMLINED": "VIDA SANITARIA",
  "FROM YOUR TAP": "DE TU TAP",
  "ONE MACHINE.": "Una máquina.",
  "FIVE TYPES OF WATER.": "Cinco tipos de agua.",
  "The JrIV produces Enagic's five water types for drinking, cooking, cosmetic and household applications.": "El JrIV produce los cinco tipos de agua de Enágic para beber, cocinar, cosméticos y aplicaciones domésticas.",
  "Cold water from your faucet": "Agua fría del grifo",
  "FILTRATION": "FILTRACIÓN",
  "High-grade activated charcoal filter": "Filtro de carbón activado de alta calidad",
  "ELECTROLYSIS": "ELECTROLISIS",
  "pH 2.5 → 11.5": "pH 2,5 → 11.5",
  "✓ FOR DRINKING": "✓ DE BEBIR",
  "pH 8.5–9.5": "pH 8,5–9,5",
  "Electrolyzed hydrogen-rich water for daily hydration, tea, cooking.": "Agua rica en hidrógeno electrolizada para hidratación diaria, té, cocina.",
  "pH 7.0": "pH 7,0",
  "Clean Water": "Agua limpia",
  "Filtered neutral water. Used for baby formula and medications.": "Agua neutra filtrada. Utilizada para fórmula para bebé y medicamentos.",
  "pH 5.5–6.0": "pH 5,5–6,0",
  "Beauty Water": "Agua de belleza",
  "Slightly acidic. Gentle facial astringent, hair rinse, glass cleaning.": "Ligeramente ácido. Astringente facial suave, enjuague de cabello, limpieza de vidrio.",
  "pH 11.0+": "pH 11,0+",
  "Strong Kangen": "Kangen fuerte",
  "High-alkaline water for kitchen degreasing and dishwashing.": "Agua alta alcalina para desengrasar y lavar platos.",
  "pH 2.5": "pH 2,5",
  "Strong Acidic": "Ácido fuerte",
  "Hypochlorous acid water for household surface sanitation.": "Agua ácida hipoclorosa para el saneamiento de la superficie familiar.",
  "* Refer to the official LeveLuk JrIV owner's manual for detailed operating guidelines for each water setting.": "* Consulte el manual oficial del propietario de LeveLuk JrIV para obtener directrices operativas detalladas para cada ajuste de agua.",
  "THE ORIGIN OF KANGEN WATER®": "EL ORIGEN DE KANGEN WATER®",
  "INSPIRED BY NATURAL SPRINGS.": "Aspirado por primaveras naturales.",
  "PERFECTED AT YOUR SINK.": "Perfeccionado en tu costado.",
  "Long before modern ionizers existed, untouched mountain streams were prized for their purity and vitality. Enagic® brings this standard into your home through precision electrolysis powered by four medical-grade platinum-titanium plates.": "Mucho antes de que existieran los ionizadores modernos, los arroyos de montaña intactos eran apreciados por su pureza y vitalidad. Enágic® trae este estándar a su hogar a través de la electrólisis de precisión alimentada por cuatro placas de platino de calidad médica.",
  "ENGINEERED FOR EFFICIENCY": "INGENIERÍA PARA LA EFICIENCIA",
  "FOUR SOLID": "CUATRO SOLIDOS",
  "The JrIV uses four solid platinum-coated titanium electrode plates to perform electrolysis. The reduced plate count helps keep energy consumption lower — 120W — while still allowing the machine to produce all five of Enagic's water types.": "El JrIV utiliza cuatro placas de electrodos de titanio recubiertas de platino sólido para realizar electrólisis. El recuento reducido de placas ayuda a mantener el consumo de energía más bajo — 120W — mientras que permite que la máquina produzca los cinco tipos de agua de Enágic.",
  "Electrolysis Process": "Proceso de electrólisis",
  "Source Tap Water": "Fuente Grifo Agua",
  "Enters through cold faucet diverter valve": "Entra a través de la válvula del desviador del grifo frío",
  "Internal Filtration": "Filtración interna",
  "High-grade antibacterial charcoal filter": "Filtro de carbón antibacteriano de alta calidad",
  "Electrolysis Chamber": "Cámara de electrólisis",
  "Dual Hose Output": "Salida de doble manguera",
  "Selected water exits upper pipe or acidic hose": "El agua seleccionada sale de la tubería superior o manguera ácida",
  "Performance Notice:": "Notificación de rendimiento:",
  "Actual pH and ORP values vary with source water chemistry, flow rate, temperature, machine condition, and operating conditions. Published specifications represent standard laboratory testing conditions.": "Los valores reales de pH y ORP varían con la química del agua de origen, el caudal, la temperatura, el estado de la máquina y las condiciones de funcionamiento.",
  "Electrode Plates": "Placas de electrodos",
  "Solid Platinum-Coated Titanium": "Titanio sólido recubierto de platino",
  "Plate Size (mm)": "Tamaño de la placa (mm)",
  "Large solid surface area": "Gran superficie sólida",
  "Power Draw": "Dibujar energía",
  "Energy-efficient operation": "Funcionamiento eficiente de la energía",
  "pH Range": "Intervalo de pH",
  "Full spectrum, 5 water types": "Espectro completo, 5 tipos de agua",
  "DESIGNED TO DO MORE": "DESIGNADO A HACER MÁS",
  "WITH LESS.": "Con menos.",
  "The JrIV operates at 120W — a lower power draw than Enagic's larger models. This reflects the machine's streamlined four-plate design, which is optimized for lower-demand households rather than maximum throughput.": "El JrIV funciona a 120W, un giro de potencia inferior al de los modelos más grandes de Enágic. Esto refleja el diseño aerodinámico de cuatro placas de la máquina, que está optimizado para hogares de menor demanda en lugar del rendimiento máximo.",
  "Touch-Button Selection": "Selección de botones táctiles",
  "Select your water mode from the front panel": "Seleccione su modo de agua desde el panel delantero",
  "Automatic Cleaning": "Limpieza automática",
  "Microcomputer-triggered internal cleaning cycles": "Ciclos de limpieza interna activados por microordenadores",
  "Smart Filter Notification": "Notificación de filtro inteligente",
  "LCD and buzzer alert when filter is due": "LCD y zumbador alerta cuando el filtro está previsto",
  "Built-In Enhancer Tank": "Tanque de refuerzo incorporado",
  "For Strong Kangen (11.0+) and Strong Acidic (2.5)": "Para Kangen fuerte (11,0+) y ácido fuerte (2.5)",
  "HONEST COMPARISON": "COMPARACIÓN DE Honestos",
  "WHICH KANGEN MACHINE": "QUE KANGEN MACHINE",
  "FITS YOUR HOME?": "¿Fiestas tu casa?",
  "Compare the streamlined JrIV against Enagic's flagship K8.": "Compare el JrIV racionalizado con el K8 insignia de Enágic.",
  "RIGHT-SIZED": "DERECHAS",
  "Junior Model": "Modelo Junior",
  "Power Rating": "Calificación de potencia",
  "Water Types": "Tipos de agua",
  "Best Suited For": "Mejor para",
  "Output Rate": "Tasa de producción",
  "Warranty (U.S.)": "Garantía (E.U.A.)",
  "MAXIMUM CAPABILITY": "CAPACIDAD MÁXIMA",
  "Flagship Model": "Modelo de buque insignia",
  "Families & Heavy Use": "Familias y uso pesado",
  "Explore K8": "Explorar K8",
  "The JrIV is not the \"cheaper K8\" — it is the right-sized Kangen machine for lower-demand households. The K8 is not necessarily better for every visitor; the correct choice depends on household size, usage, and water conditions.": "El JrIV no es el \"K8 barato\", es la máquina Kangen de tamaño derecho para los hogares de menor demanda. El K8 no es necesariamente mejor para cada visitante; la elección correcta depende del tamaño del hogar, el uso y las condiciones de agua.",
  "IS JRIV RIGHT FOR YOU?": "¿Jriv está bien para ti?",
  "IS JRIV": "ES JRIV",
  "RIGHT FOR YOU?": "¿Justo para ti?",
  "YES IF": "SÍ SI",
  "Strong match for your situation": "Coincidencia fuerte para su situación",
  "You're living alone": "Estás viviendo solo.",
  "You're a couple": "Son pareja.",
  "Your household has lower water-output requirements": "Su hogar tiene menores requisitos de salida de agua",
  "You want the full five-water-type Kangen® experience": "Usted quiere la experiencia completa de Kangen® de cinco tipos de agua",
  "You prefer a streamlined, energy-efficient model": "Prefieres un modelo racionalizado y eficiente en energía",
  "CONSIDER K8 IF": "CONSIDERACIÓN K8 SI",
  "Higher output requirements": "Mayores necesidades de productos",
  "You have a larger household": "Tienes una casa más grande",
  "You expect heavier continuous output requirements": "Usted espera requisitos de salida continua más pesados",
  "You want Enagic's flagship eight-plate configuration": "Quieres la configuración insignia de ocho placas de Enágic",
  "You need faster filling of multiple large bottles": "Usted necesita llenado más rápido de múltiples botellas grandes",
  "You want the longest U.S. warranty (5 years)": "Usted quiere la garantía más larga de los EE.UU. (5 años)",
  "Not sure? Let's figure it out together": "Vamos a averiguarlo juntos.",
  "OFFICIAL U.S. REFERENCE DATA": "DATOS OFICIALES DE LA REFERENCIA DE LOS ESTADOS UNIDOS",
  "LeveLuk JrIV Specifications": "Especificaciones LeveLuk JrIV",
  "ELECTRODE\nPLATES": "PLATAS DE ELECTRODO",
  "WATER\nTYPES": "TIPOS DE GUERRA",
  "POWER": "PODER",
  "pH\nRANGE": "Rango de pH",
  "WARRANTY\n(U.S.)": "GARANTÍA (E.U.A.)",
  "WEIGHT": "PESO",
  "Specification": "Especificación",
  "Official Reference Value": "Valor de referencia oficial",
  "Electrode Material": "Material del electrodo",
  "Platinum-coated titanium": "Titanio recubierto con platino",
  "Plate Size": "Tamaño de la placa",
  "Published pH Range": "Intervalo de pH publicado",
  "Power Consumption": "Consumo de energía",
  "Total Weight": "Peso total",
  "Dimensions (W × H × D)": "Dimensiones (W × H × D)",
  "Kangen Water Production Rate": "Tasa de producción de agua de Kangen",
  "Acidic Water Production Rate": "Tasa de producción de agua ácida",
  "Strong Acidic Production Rate": "Tasa de producción ácida fuerte",
  "Operation": "Funcionamiento",
  "Fully automatic microcomputer": "Microordenador totalmente automático",
  "Languages Displayed": "Idiomas mostrados",
  "Referenced U.S. Warranty": "Garantía de EE.UU. referenciada",
  "Specifications and included components can vary by geographic region. Confirm local voltage & market specs prior to ordering.": "Las especificaciones y componentes incluidos pueden variar según la región geográfica. Confirme las especificaciones locales de voltaje y mercado antes de ordenar.",
  "OWNERSHIP EXPERIENCE": "EXPERIENCIA DE LA PROPIEDAD",
  "Understand the Ownership Experience": "Comprender la experiencia de propiedad",
  "Internal Filtration Details": "Detalles de filtración interna",
  "The JrIV includes an internal FC1 high-grade filter utilizing premium antibacterial activated charcoal and calcium sulfite. It effectively reduces chlorine odor, taste, and sediment from municipal source water. It is not certified as a universal reverse-osmosis purifier.": "El JrIV incluye un filtro interno FC1 de alta calidad que utiliza carbón activado antibacterial de primera calidad y sulfito de calcio. Reduce eficazmente el olor al cloro, el sabor y el sedimento del agua de la fuente municipal.",
  "Filter Replacement Schedule": "Programa de sustitución de filtros",
  "Automatic & Periodic Cleaning": "Limpieza automática y periódica",
  "Manufacturer Warranty Terms": "Condiciones de garantía del fabricante",
  "View Official Enagic JrIV Product Page": "Ver la página oficial del producto JrIV",
  "CLEAR ANSWERS": "Respuestas claras",
  "Questions About the LeveLuk JrIV": "Preguntas sobre el LeveLuk JrIV",
  "What is the LeveLuk JrIV?": "¿Qué es el LeveLuk JrIV?",
  "How is JrIV different from the K8?": "¿En qué se diferencia JrIV del K8?",
  "How many electrode plates does the JrIV have?": "¿Cuántas placas de electrodo tiene el JrIV?",
  "What five water types does it produce?": "¿Qué cinco tipos de agua produce?",
  "Who is the JrIV recommended for?": "¿Para quién se recomienda el JrIV?",
  "Can families use the JrIV?": "¿Pueden las familias usar el JrIV?",
  "How much water can the JrIV produce?": "¿Cuánta agua puede producir el JrIV?",
  "Does the JrIV clean itself automatically?": "¿El JrIV se limpia automáticamente?",
  "How will I know when to change the filter?": "¿Cómo sabré cuándo cambiar el filtro?",
  "What is the electrolysis enhancer tank?": "¿Qué es el tanque potenciador de electrólisis?",
  "What is the warranty?": "¿Cuál es la garantía?",
  "How do I order the JrIV?": "¿Cómo ordeno el JrIV?",
  "Can I speak with my distributor before choosing?": "¿Puedo hablar con mi distribuidor antes de elegir?",
  "NOT SURE WHICH MACHINE FITS YOUR HOME?": "¿No está seguro de qué máquina le pega a su casa?",
  "Talk Directly with": "Hable directamente con",
  "\"I shared the JrIV with you because not everyone needs the largest machine. I'll help you review your household size, water source, faucet, expected usage, and budget — so you choose honestly.\"": "\"Compartí el JrIV contigo porque no todos necesitan la máquina más grande. Te ayudaré a revisar el tamaño de tu casa, fuente de agua, grifo, uso esperado y presupuesto, así que eliges honestamente\".",
  "About the JrIV": "Acerca del JrIV",
  "Compare with K8": "Comparar con K8",
  "THE KANGEN EXPERIENCE.": "La experiencia de Kangen.",
  "RIGHT-SIZED FOR YOUR LIFE.": "Tiene razón para su vida.",
  "Five water types. Four platinum-coated titanium plates. One streamlined way to bring Kangen Water® into your home.": "Cinco tipos de agua. Cuatro placas de titanio con recubrimiento de platino. Una forma aerodinámica de traer Kangen Water® a su hogar.",
  "Get Started with JrIV": "Empezar con JrIV",
  "The LeveLuk JrIV is a water ionization system, not a substitute for safe source water, appropriate filtration, plumbing assessment, or medical care. Actual pH, ORP, flow rate, and water characteristics vary with source-water chemistry, pressure, temperature, flow, machine condition, settings, and maintenance. Product specifications, voltage, included components, warranty, availability, and permitted claims vary by market. Follow the official manual and local Enagic guidance.": "El LeveLuk JrIV es un sistema de ionización del agua, no un sustituto del agua de fuente segura, filtración apropiada, evaluación de plomería o atención médica. Las características reales de pH, ORP, caudal y agua varían con la química de la fuente de agua, presión, temperatura, flujo, condición de la máquina, ajustes y mantenimiento. Las especificaciones del producto, voltaje, componentes incluidos, garantía, disponibilidad y reclamaciones permitidas varían según el mercado.",
  "Go back": "Regresa",
  "True Legacy World Home": "Inicio de True Legacy World",
  "Select Language": "Seleccionar idioma"
})
