// Generated from exact text that remained English when the Spanish locale was active.
// Keep brand names and product specifications unchanged when reviewing updates.
export const SpanishLegacyCore: Readonly<Record<string, string>> = Object.freeze({
  "Leader": "Líder",
  "Contact Your Distributor": "Contacta a tu distribuidor",
  "Contactar a Your Distributor": "Contacta a tu distribuidor",
  "8 Platinum Plates · -850mV ORP · 5 pH Types": "8 placas de platino · ORP de -850 mV · 5 tipos de pH",
  "7 Plates · 2.5–11.5 pH · -800mV · 5 Year Warranty": "7 placas · pH 2.5–11.5 · -800 mV · 5 años de garantía",
  "12 Plates · High Flow · 2.5–11.5 pH · 3 Year Warranty": "12 placas · Alto flujo · pH 2.5–11.5 · 3 años de garantía",
  "4 Plates · Low Energy · 2.5–11.5 pH · 3 Year Warranty": "4 placas · Bajo consumo · pH 2.5–11.5 · 3 años de garantía",
  "EN": "ES",
  "featured markets with True Legacy members and leaders": "mercados con miembros y líderes de True Legacy",
  "years of Enagic innovation": "años de innovación Enágica",
  "Morocco · Colombia · USA": "Marruecos · Colombia · EEUU",
  "Coach Mehdi": "Entrenador Mehdi",
  "Malaysia · UAE · Nigeria": "Malasia · Emiratos Árabes Unidos · Nigeria",
  "Coach Simon Loh": "Entrenador Simon Loh",
  "Malaysia · India · Global": "Malasia · India · Global",
  "USA · Global": "EEUU · Global",
  "Los Angeles · USA": "Los Ángeles · Estados Unidos",
  "Coach Magaly": "Entrenador Magaly",
  "Malaysia · Singapore · Dubai · Global": "Malasia · Singapur · Dubai · Global",
  "True Legacy community ›": "Comunidad del verdadero legado ›",
  "Global · English": "Global · Inglés",
  "Unlock Your True Legacy": "Desbloquee su verdadero legado",
  "La Revolución del Biohacking Llega a LATAM": "La Revolución del Biohacking en Latam",
  "Cada jueves · 7:00 PM Colombia / 8:00 PM Eastern": "Colombia / 8:00 PM Este",
  "True Legacy Duo": "Duo verdadero legado",
  "True Legacy World": "El verdadero mundo del legado",
  "True Legacy LATAM": "Verdadero legado LATAM",
  "True Legacy World.": "Verdadero Mundo Legado.",
  "Toggle menu": "Conmutar menú",
  "Previous leader": "Líder anterior",
  "Go to leader 1": "Ir al líder 1",
  "Go to leader 2": "Ir al líder 2",
  "Go to leader 3": "Ir a líder 3",
  "Go to leader 4": "Vaya al líder 4",
  "Go to leader 5": "Ve al líder 5",
  "Go to leader 6": "Ve al líder 6",
  "Go to leader 7": "Ve al líder 7",
  "Go to leader 8": "Ve al líder 8",
  "Go to leader 9": "Ve al líder 9",
  "Go to leader 10": "Ve al líder 10",
  "Next leader": "Siguiente líder",
  "Previous testimonial": "Anterior testimonio",
  "Open testimonial from Doina Rotar": "Testimonio abierto de Doina Rotar",
  "Open testimonial from Egbert Nah": "Testimonio abierto de Egbert Nah",
  "Open testimonial from Mok E Lin": "Testimonio abierto de Mok E Lin",
  "Open testimonial from Nigara Ismailova": "Testimonio abierto de Nigara Ismailova",
  "Open testimonial from Ryan Pool": "Testimonio abierto de Ryan Pool",
  "Open testimonial from Sofia Cohen": "Testimonio abierto de Sofía Cohen",
  "Open testimonial from Thomas & Kristen Sinner": "Testimonio abierto de Thomas & Kristen Sinner",
  "Open testimonial from Veronica Calafat": "Testimonio abierto de Veronica Calafat",
  "Next testimonial": "Próximo testimonio",
  "United States": "Estados Unidos",
  "Morocco": "Marruecos",
  "Brazil": "Brasil",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  "Malaysia": "Malasia",
  "Turkey": "Turquía",
  "Spain": "España",
  "European Union": "Unión Europea",
  "Back to top": "Volver al principio",
  "Enagic® · True Legacy": "Enágic® · Verdadero legado",
  "emGuarde GO™ (Set of 2)": "emGuarde GOTM (Set de 2)",
  "Out of Stock": "Fuera de existencia",
  "Home": "Inicio",
  "Install True Legacy": "Instalar un verdadero legado",
  "Open your dashboard and training from your home screen.": "Abra su tablero y entrenamiento desde su pantalla de inicio.",
  "Install": "Instalar",
  "Hide": "Ocultar",
  "Today": "Hoy",
  "Contacts": "Contactos",
  "Academy": "Academia",
  "Share": "Compartir",
  "Bookings": "Reservas",
  "Library": "Biblioteca",
  "Settings": "Configuración",
  "Install True Legacy app": "Instalar la aplicación True Legacy",
  "Dismiss install invitation": "Desestimar invitación de instalación",
  "Hide navigation bar": "Ocultar la barra de navegación",
  "True Legacy app navigation": "Navegación de aplicaciones True Legacy",
  "True Legacy Verified Leaders & Distributors": "Líderes y distribuidores verificados del verdadero legado",
  "Loading verified leaders…": "Cargando líderes verificados...",
  "Portrait Studio": "Estudio de retratos",
  "True Legacy Live Events | Global and LATAM": "True Legacy Live Events, Global y LATAM",
  "Leader | True Legacy World": "Líder, Mundo Legado Verdadero",
  "Loading verified profile…": "Cargando el perfil verificado...",
  "True Legacy Team | Leveluk K8 Kangen Water® | True Legacy": "True Legacy Team, Leveluk K8 Kangen Water®, True Legacy",
  "Leader:": "Líder:",
  "Your Distributor": "Su distribuidor",
  "Better water,": "Mejor agua,",
  "freshly made": "recién hecho",
  "at your tap.": "en tu grifo.",
  "True Legacy Team": "Equipo del verdadero legado",
  "Independent Enagic Distributor · True Legacy Leader": "Distribuidor Enágico Independiente · Líder Legado Verdadero",
  "English": "Español",
  "pH 8.5 – 9.5": "pH 8,5 – 9,5",
  "Primary Household Uses:": "Usos primarios del hogar:",
  "Usage & Handling Note:": "Nota de & manejo:",
  "Enagic holds ISO 13485 (Medical Devices Quality Management System), ISO 9001, ISO 14001, and the Water Quality Association (WQA) Gold Seal certification.": "Enágic posee la certificación ISO 13485 (Sistema de Gestión de Calidad de Dispositivos Médicos), ISO 9001, ISO 14001, y la certificación Gold Seal de la Asociación de Calidad del Agua (WQA).",
  "TRUE LEGACY WORLD": "EL VERDADERO MUNDO DE LA LEGACIÓN",
  "All Rights Reserved.": "Todos los derechos reservados.",
  "Privacy Policy & Terms": "Política de privacidad y términos",
  "Back to Your Distributor's Profile": "Volver al perfil de su distribuidor",
  "Back to True Legacy Team's Profile": "Volver al perfil del equipo de True Legacy",
  "Shared by True Legacy Team": "Compartido por True Legacy Team",
  "Switch language to EN": "Cambiar el idioma a EN",
  "Switch language to ES": "Cambiar el idioma a ES",
  "Switch language to FR": "Cambiar el idioma a FR",
  "Switch language to PT": "Cambiar el idioma a PT",
  "Leveluk K8 4-Minute Demonstration": "Demostración de 4 minutos de Leveluk K8",
  "The Enagic emGuarde™ · Patented Close-Body Personal Protection · True Legacy Leader": "Enagic emGuarde™ · Protección personal patentada de proximidad corporal · Líder de True Legacy",
  "True": "True",
  "True Legacy Leader": "Verdadero líder del legado",
  "Video Language:": "Idioma del vídeo:",
  "English (~8m)": "Inglés (~8m)",
  "Español (~8m)": "(~8m)",
  "Complete Enagic emGuarde™ Overview": "Resumen completo de EmGuardeTM",
  "Patent Identifier": "Identificador de patentes",
  "Internal Cellular Hydration": "Hidratación celular interna",
  "External Harmonization": "Armonización externa",
  "Privacy Policy": "Política de privacidad",
  "Terms of Service": "Condiciones de servicio",
  "Compliance & Disclaimers": "Cumplimiento y descargos",
  "Back to True's Profile": "Volver al perfil de True",
  "Back to True Legacy Leader's Profile": "Volver al perfil del líder del verdadero legado",
  "Shared by True Legacy Leader": "Compartido por el verdadero líder del legado",
  "The Enagic emGuarde Presentation": "La Enágica EmGuarde Presentación",
  "True Legacy Duo · Water & Environment | Mehdi Cohen": "Verdadero legado Duo · Agua y Medio Ambiente, Mehdi Cohen",
  "JAPANESE MED-TECH": "JAPONESE MED-TECH",
  "Pillar 01: Water Vitality": "Pilar 01: Vitalidad del agua",
  "PATENTED HARMONIC": "HARMONIC",
  "Pillar 02: Environmental Calm": "Pilar 02: Calma ambiental",
  "Official presentation videos localized for": "Videos oficiales de presentación localizados para",
  ". Sound starts only upon your explicit play interaction.": ". El sonido comienza sólo con su interacción de juego explícita.",
  "PATENTED RESONANCE": "RESPONSABILIDAD ATENIDA",
  "Dual-Unit Portable Set": "Conjunto portátil de doble unidad",
  "EVERYDAY HARMONY": "Todos los días HARMONY",
  "pH 2.5 to pH 11.5 Continuous Generation": "pH 2,5 a pH 11.5 Generación continua",
  "PILLAR 01: INTERNAL WELLNESS": "PILLAR 01: BIENESTAR INTERNAL",
  "PILLAR 02: ENVIRONMENTAL CALM": "PILLAR 02: CAMPO AMBIENTAL",
  "Dual-Unit Synchronized Set": "Conjunto sincronizado de doble unidad",
  "Up to 72 Hours USB-C Battery · 3m Diameter Range": "Batería USB-C hasta 72 horas · Intervalo de diámetro de 3m",
  "THE DUO ADVANTAGE": "LA VENTAJA DE DUO",
  "OFFICIAL PRODUCT SHOWCASE": "MUESTREO DE PRODUCTOS OFICIALES",
  "FLAGSHIP IONIZER": "IONIZER DE LA FLAGA",
  "HARMONIC RESONATOR": "RESONADOR HARMÓNICO",
  "Set of 2 Units": "Conjunto de 2 Unidades",
  "SIDE-BY-SIDE SPECIFICATIONS": "ESPECIFICACIONES FINANCIERAS",
  "INDIVIDUAL DEEP-DIVES": "DIVISIONES INDIVIDUALES",
  "EXPLORE THE BUSINESS OPPORTUNITY": "EXPLORAR LA OPORTUNIDAD EMPRESARIAL",
  "ANSWERS & CLARITY": "RESPUESTAS Y CLARIDAD",
  "The True Legacy Duo": "El verdadero legado Duo",
  "Two distinct product categories. One connected starting story.": "Dos categorías distintas de productos.",
  "Go back": "Regresa",
  "Shared by Mehdi Cohen": "Compartido por Mehdi Cohen",
  "The True Legacy Duo Presentation": "La presentación del verdadero legado Duo",
  "Kangen Ukon® | Okinawan Turmeric | True Legacy": "Kangen Ukon® | Cúrcuma de Okinawa | True Legacy",
  "Patented Seaweed Softgel · 100 Capsules": "Algas patentadas Softgel · 100 cápsulas",
  "MADE IN JAPAN": "EN JAPÓN",
  "KANGEN WATER® PROCESSED": "KANGEN WATER® PROCESADO",
  "Pristine subtropical microclimate with mineral-dense volcanic soil, ocean mist, and clean rain.": "Microclima subtropical pristino con suelo volcánico mineral-dense, niebla oceánica y lluvia limpia.",
  "Explore Enagic® Kangen Water® Ionization Technology": "Explore la tecnología de ionización Enágic® Kangen Water®",
  "Kangen Ukon® Tea": "Té Kangen Ukon®",
  "Kangen Ukon® Soap": "Jabón Kangen Ukon®",
  "ENAGIC KANGEN FOODS": "ALIMENTOS ENAGICOS DE KANGEN",
  "Every product undergoes stringent Japanese cleanroom validation before being cleared for global shipping.": "Cada producto se somete a una estricta validación japonesa de salas limpias antes de ser autorizado para el envío global.",
  "Morning Wellness Ritual": "Mañana Bienestar Ritual",
  "Fresh Kangen Water® + Kangen Ukon® Sigma softgels on natural stone slate.": "Kangen Water® fresca y cápsulas blandas Kangen Ukon® Sigma sobre una pizarra de piedra natural.",
  "Kangen Ukon® Sigma Dietary Supplement": "Kangen Ukon® Sigma Suplemento dietético",
  "Ionization Technology": "Tecnología de ionización",
  "Botanical Nutrition": "Nutrición Botánica",
  "Back to Mehdi's Profile": "Volver al perfil de Mehdi",
  "Back to Mehdi Cohen's Profile": "Volver a Perfil de Mehdi Cohen",
  "Kangen Ukon® — The Story of Okinawan Turmeric": "Kangen Ukon® — La historia de Okinawan Cúrcuma",
  "jane@example.com": "jane@ejemplo.com",
  "Enagic®": "Enágico®",
  "Showcase": "Vitrina",
  "Total Internal & External Cellular Synergy": "Sinergia celular interna y externa total",
  "Experience 8-plate active molecular hydrogen (H₂) hydration alongside patented 3-meter harmonic resonance technology to harmonize electro smoke and EMF radiation noise.": "Experimente una hidratación de hidrógeno molecular activo (H2) de 8 placas junto con tecnología patentada de resonancia armónica de 3 metros para armonizar el humo electro y el ruido de radiación EMF.",
  "Leveluk K8 Water System": "Sistema de agua Leveluk K8",
  "emGuarde GO (Set of 2)": "emGuarde GO (Set de 2)",
  "Enagic® Certified": "Certificado Enágic®",
  "pH Range": "Intervalo de pH",
  "Up to -850 mV": "Hasta -850 mV",
  "Harmonic Resonance Chip": "Chip de resonancia armónica",
  "Suppresses High-Frequency Noise": "Suprime el ruido de alta frecuencia",
  "Anespa DX Mineral Ion Shower": "Ducha de iones minerales Anespa DX",
  "Slightly Acidic 6.8 – 7.2 pH": "Ligeramente ácida 6,8 – 7,2 pH",
  "Active Mineral Infusion": "Infusión Mineral Activa",
  "Okinawa Wild Turmeric": "Okinawa Cúrcuma silvestre",
  "Infused with Strong Kangen 11.5": "Infundido con Kangen fuerte 11.5",
  "High Curcuminoid Potency": "Alta potencia curcuminoidea",
  "PDF Guide": "Guía PDF",
  "Inquire": "Consultar",
  "Cleanser · Essence Lotion · Radiance Cream": "Limpiador · Loción de esencia · Crema de radiación",
  "A5 Grade · Japan & US Availability": "Grado A5 · Japón y Estados Unidos Disponibilidad",
  "Model": "Modelo",
  "Plates / Core Tech": "Placas / Core Tech",
  "ORP / Signal": "ORP / Señal",
  "Warranty": "Garantía",
  "Primary Application": "Aplicación primaria",
  "Ultimate Home Antioxidant & Hydration": "Máxima capacidad antioxidante e hidratación para el hogar",
  "8 Solid Plates": "8 placas sólidas",
  "7 Solid Plates": "7 placas sólidas",
  "4 Solid Plates": "4 placas sólidas",
  "5 Years": "5 años",
  "3 Years": "3 años",
  "12 Plates (Dual Chamber)": "12 placas (doble cámara)",
  "Futamata Mineral Spa": "Spa mineral Futamata",
  "6.8 – 7.2 pH (Chlorine Free)": "pH 6.8–7.2 (sin cloro)",
  "Up to -800 mV": "Hasta -800 mV",
  "Families & Daily Performance Standard": "Familias y rendimiento diario estándar",
  "Up to -850 mV (High Flow)": "Hasta -850 mV (alto flujo)",
  "High Volume, Clinics & Commercial Spas": "Alto volumen, clínicas y spas comerciales",
  "Up to -450 mV": "Hasta -450 mV",
  "Singles, Students & Compact Spaces": "Solteros, estudiantes y espacios compactos",
  "Mineral Hot Spring Ionization": "Ionización mineral del manantial caliente",
  "Shower Water, Hair & Sensitive Skin": "Agua de ducha, cabello y piel sensible",
  "Suppresses Noise Frequencies": "Suprime las frecuencias de ruido",
  "Electro Smoke & EMF Environmental Defense · Travel": "Electro Humo y Defensa Ambiental EMF · Viajes",
  "Kangen Water® Ionizers Guide": "Guía de ionizadores Kangen Water®",
  "Comprehensive 8-page overview of Leveluk K8, SD501, Super 501, and Jr IV.": "Resumen completo de 8 páginas de Leveluk K8, SD501, Super 501, y Jr IV.",
  "Open Official PDF": "Abrir PDF oficial",
  "Anespa DX Mineral Spa Brochure": "Anespa DX Mineral Spa Folleto",
  "Full specification guide on hot spring minerals and chlorine removal.": "Guía completa de especificaciones sobre minerales de manantial y eliminación de cloro.",
  "Kangen Ukon® Sigma Product Guide": "Guía del producto Kangen Ukon® Sigma",
  "Okinawan turmeric softgel harvesting, patent packaging, and health science.": "Okinawan cúrcuma softgel cosecha, embalaje de patentes, y ciencias de la salud.",
  "Machine Care & Maintenance Guide": "Guía de cuidado y mantenimiento de la máquina",
  "Deep cleaning, filter replacements, and long-term ionizer preservation.": "Limpieza profunda, reemplazos de filtros y preservación del ionizador a largo plazo.",
  "Browse products available to buy": "Buscar productos disponibles para comprar",
  "Switch to EN": "Cambiar a EN",
  "Switch to ES": "Cambiar a ES",
  "Switch to FR": "Cambiar a FR",
  "Switch to PT": "Cambiar a PT"
})
