// Generated from exact text that remained English when the Spanish locale was active.
// Keep brand names and product specifications unchanged when reviewing updates.
export const SpanishLegacyAcademy: Readonly<Record<string, string>> = Object.freeze({
  "8. Live Training & Calls": "8. Entrenamientos y llamadas en vivo",
  "ONE ACADEMY · SEVEN LEARNING PATHS": "UNA ACADEMIA · SIETE RUTAS DE APRENDIZAJE",
  "Business Fundamentals": "Fundamentos del negocio",
  "Leadership Development": "Desarrollo del liderazgo",
  "10+ core foundation modules · Live weekly global masterclasses · Private CRM vault": "Más de 10 módulos fundamentales · Clases magistrales globales semanales en vivo · Bóveda privada del CRM",
  "1. Product Mastery": "1. Dominio de los productos",
  "2. Business Fundamentals": "2. Fundamentos del negocio",
  "3-Pillar content system": "Sistema de contenido de 3 pilares",
  "6. Leadership Development": "6. Desarrollo del liderazgo",
  "True Legacy Academy | Private Leadership & Business-Building Education": "Academia del Legado Verdadero, Liderazgo Privado y Educación para la Construcción de Empresas",
  "EN": "ES",
  "True Legacy Academy · Exclusive Team Resource": "Verdadera Academia del Legado · Recursos exclusivos del equipo",
  "YOU DON’T HAVE TO FIGURE THIS OUT ALONE.": "No tienes que entender esto solo.",
  "A business opportunity is only as powerful as your ability to build it.": "Una oportunidad de negocio es tan poderosa como su capacidad para construirla.",
  "Enagic gives independent distributors access to an established global company, patented medical technologies, and a proven business model. True Legacy adds the private education, systems, leadership development, and practical training designed to help our distributors execute responsibly.": "Enágic da a los distribuidores independientes acceso a una empresa global establecida, tecnologías médicas patentadas y un modelo de negocio probado. True Legacy añade la educación privada, sistemas, desarrollo de liderazgo y formación práctica diseñada para ayudar a nuestros distribuidores a ejecutar responsablemente.",
  "THE VEHICLE ALREADY EXISTS. WE HELP DEVELOP THE DRIVER.": "El vehículo ya existe.",
  "Preview the Syllabus": "Vista previa del Syllabus",
  "Explore the Opportunity": "Explore la oportunidad",
  "🔒 Private training infrastructure included exclusively for authorized True Legacy distributors": ", infraestructura de capacitación privada incluida exclusivamente para distribuidores autorizados True Legacy",
  "Proprietary Team Curriculum": "Plan de estudios del equipo propietario",
  "WELCOME TO YOUR BUSINESS-BUILDING ROADMAP": "Bienvenido a tu plan de construcción de negocios",
  "Here is a preview of the proprietary curriculum available inside the private True Legacy portal. Full video masterclasses, diagnostic frameworks, and downloadable templates are unlocked for verified distributors.": "Aquí hay una vista previa del currículo propietario disponible dentro del portal privado True Legacy. Clases maestras de vídeo completas, marcos de diagnóstico y plantillas descargables se desbloquean para distribuidores verificados.",
  "truelegacyworld.com/academy · Private Leadership Portal": "truelegacyworld.com/academy · Portal de Liderazgo Privado",
  "All Pillars": "Todos los pilares",
  "Foundation": "Fundación",
  "Product Mastery": "Maestría en productos",
  "Communication & Closing": "Comunicación y cierre",
  "Systems & CRM": "Sistemas & CRM",
  "Leadership Structure": "Estructura de liderazgo",
  "foundation": "fundación",
  "Team Exclusive": "Equipo exclusivo",
  "True Legacy Executive Leaders": "Líderes ejecutivos del verdadero legado",
  "Curriculum Preview:": "Previsualización del currículo:",
  "View Syllabus Outline": "Ver esquema de Syllabus",
  "PDF guides": "Guías PDF",
  "product": "producto",
  "leadership": "liderazgo",
  "Coach Ming-Way Sia & Simon Loh": "Entrenador Ming-Way Sia & Simon Loh",
  "systems": "sistemas",
  "communication": "comunicación",
  "True Legacy Academy Trainers": "Entrenadores de la Academia del Legado Verdadero",
  "Explore All 8 Knowledge Pillars": "Explore los 8 pilares del conocimiento",
  "Core Philosophy": "Filosofía básica",
  "THE OPPORTUNITY IS SIMPLE.": "La oportunidad es simple.",
  "BECOMING SKILLED TAKES DEVELOPMENT.": "Llegar a ser asesinado requiere desarrollo.",
  "Having access to a powerful business model does not automatically teach someone how to communicate with confidence, ask diagnostic questions, present medical technology, lead a team, or pioneer an emerging market.": "Tener acceso a un poderoso modelo de negocio no enseña automáticamente a alguien cómo comunicarse con confianza, hacer preguntas de diagnóstico, presentar tecnología médica, dirigir un equipo o ser pionero en un mercado emergente.",
  "Those are learned skills.": "Esas son habilidades aprendidas.",
  "True Legacy Academy exists to dramatically shorten your learning curve. Instead of handing you a distributor ID and wishing you good luck, we provide an engineered path designed to help you understand what you are building, why you are building it, and exactly what skill to master next.": "True Legacy Academy existe para acortar drásticamente su curva de aprendizaje. En lugar de entregarle una identificación de distribuidor y desearle buena suerte, proporcionamos un camino diseñado para ayudarle a entender lo que está construyendo, por qué lo está construyendo, y exactamente qué habilidad para dominar a continuación.",
  "Our Core Promise": "Nuestra promesa principal",
  "“YOU DON’T NEED TO KNOW EVERYTHING BEFORE YOU START.": "“No necesitas saber todo antes de empezar.",
  "YOU NEED TO BE WILLING TO LEARN.”": "Tienes que estar dispuesto a aprender.",
  "Skill Progression Architecture": "Arquitectura de progresión de habilidades",
  "FROM NEW DISTRIBUTOR TO INDEPENDENT LEADER": "DE NUEVO DISTRIBUTOR A LÍDER INDEPENDIENTE",
  "We measure advancement through capability and skill mastery, not hype. Follow the 5-stage progression designed for duplicable global success.": "Medimos el avance a través de la capacidad y el dominio de las habilidades, no del bombo. Siga la progresión de 5 etapas diseñada para lograr el éxito mundial.",
  "STAGE 1": "ETAPA 1",
  "FOUNDATION": "FUNDACIÓN",
  "Understand what you have": "Entiende lo que tienes",
  "Enagic fundamentals": "Fundamentos enágicos",
  "Product ecosystem & science": "Ecosistema de productos y ciencia",
  "Compliance & ethics": "Cumplimiento y ética",
  "Setting expectations & vision": "Establecer expectativas y visión",
  "Phase 0": "Fase 0",
  "· Capability Milestone": "· Capacidad Milestone",
  "STAGE 2": "ETAPA 2",
  "COMMUNICATION": "COMUNICACIÓN",
  "Learn how to talk about it": "Aprende a hablar de ello",
  "Starting conversations": "Iniciando conversaciones",
  "Asking diagnostic questions": "Hacer preguntas de diagnóstico",
  "Storytelling framework": "Marco de narración",
  "Resolving objections": "Objeciones negativas",
  "STAGE 3": "ETAPA 3",
  "BUILDING": "B",
  "Turn knowledge into activity": "Convertir el conocimiento en actividad",
  "Prospecting & pipeline CRM": "Prospección y tubería CRM",
  "DUO demonstrations": "Demostraciones DUO",
  "Digital business storefront": "Tienda digital de negocios",
  "Customer follow-up systems": "Sistemas de seguimiento de los clientes",
  "STAGE 4": "ETAPA 4",
  "LEADERSHIP": "LÍDERES",
  "Learn how to develop others": "Aprenda a desarrollar a otros",
  "Coaching & duplication": "Coaching & duplicación",
  "Team culture & accountability": "Cultura y responsabilidad del equipo",
  "Training other builders": "Capacitación de otros constructores",
  "Independent market strategy": "Estrategia de mercado independiente",
  "STAGE 5": "ETAPA 5",
  "Think beyond yourself": "Piensa más allá de ti mismo",
  "Emerging market entry": "Entrada en los mercados emergentes",
  "Cross-border collaboration": "Colaboración transfronteriza",
  "Regional live event scale": "Escala regional de eventos en vivo",
  "Long-term legacy building": "Construcción del legado a largo plazo",
  "LEARN IT.": "Apréndelo.",
  "DO IT.": "Hazlo.",
  "TEACH IT.": "Enséñenlo.",
  "DUPLICATE IT.": "Dupliquenlo.",
  "Structured First Steps": "Primeros pasos estructurados",
  "YOUR FIRST SIX WEEKS SHOULDN’T FEEL RANDOM.": "TU PRIMERA SEIS SEMANAS NO SENTIRÍA RANDOM.",
  "New distributors need clarity before complexity. The True Legacy onboarding path gives you a structured weekly focus instead of overwhelming you with information all at once.": "Los nuevos distribuidores necesitan claridad antes de la complejidad. La ruta de embarque True Legacy te ofrece un enfoque semanal estructurado en lugar de abrumarte con información a la vez.",
  "WEEK 1": "Semana 1",
  "Orientation": "Orientación",
  "Foundation & Ecosystem": "Fundación y ecosistema",
  "Understand the product science, the compensation model, community guidelines, and align your personal goals.": "Entiende la ciencia del producto, el modelo de compensación, las directrices comunitarias y alinea tus metas personales.",
  "Included in Distributor Launch Kit": "Incluido en el kit de lanzamiento del distribuidor",
  "WEEK 2": "Semana 2",
  "Authenticity": "Autenticidad",
  "Your Personal Story": "Su historia personal",
  "Learn how to communicate your why naturally and ethically, without sounding like a salesperson or using canned scripts.": "Aprende a comunicar tu porqué de forma natural y ética, sin sonar como un vendedor o usando guiones enlatados.",
  "WEEK 3": "Semana 3",
  "Communication": "Comunicación",
  "High-Value Conversations": "Conversaciones de alto valor",
  "Master asking diagnostic questions, identifying prospect needs, and starting meaningful discussions about hydration & business.": "Máster haciendo preguntas diagnósticas, identificando necesidades potenciales y comenzando discusiones significativas sobre hidratación y negocios.",
  "WEEK 4": "Semana 4",
  "Presentation": "Presentación",
  "Demonstrations & Presentations": "Demostraciones y presentaciones",
  "Learn how to run clean, impactful K8 & emGuarde demonstrations and use True Legacy recorded video presentations.": "Aprenda cómo ejecutar demostraciones de K8 y emGuarde limpias e impactantes y utilice presentaciones de vídeo grabadas True Legacy.",
  "WEEK 5": "Semana 5",
  "Infrastructure": "Infraestructura",
  "Building Your Daily System": "Construyendo su sistema diario",
  "Set up your private CRM leads pipeline, define your daily method of operation, and utilize digital follow-up tools.": "Configure su tubería privada de leads CRM, defina su método diario de operación y utilice herramientas de seguimiento digitales.",
  "WEEK 6": "Semana 6",
  "Duplication": "Duplicación",
  "Leadership & Duplication": "Liderazgo y duplicación",
  "Learn how to onboard your first direct partner through this exact same 6-week framework with total confidence.": "Aprenda cómo a bordo de su primer socio directo a través de este mismo marco exactamente 6 semanas con total confianza.",
  "Complete Education Suite": "Suite de educación completa",
  "EVERYTHING YOU NEED TO KEEP DEVELOPING.": "Todo lo que necesitas para seguir desarrollando.",
  "Eight comprehensive training departments covering every aspect of high-level independent distributor operations.": "Ocho departamentos de capacitación integral que abarcan todos los aspectos de las operaciones de distribuidores independientes de alto nivel.",
  "Comprehensive training on Kangen Water, Leveluk K8, emGuarde GO, Ukon, and certified medical applications.": "Capacitación integral sobre agua de Kangen, Leveluk K8, emGuarde GO, Ukon, y aplicaciones médicas certificadas.",
  "Water ionization science": "Ciencia de la ionización del agua",
  "EMF harmonization physics": "Física de armonización EMF",
  "Approved demonstration scripts": "Scripts de demostración aprobados",
  "Complete Course Series": "Serie completa de cursos",
  "Mastering the patented 8-Point compensation plan, distributor rank structures, compliance, and organization building.": "Dominar el plan patentado de compensación de 8 puntos, estructuras de rango de distribuidor, cumplimiento y construcción de organización.",
  "Direct vs group sales": "Ventas directas frente a ventas colectivas",
  "Sustainable rank planning": "Planificación sostenible de rangos",
  "Diagnostic questioning frameworks, invitation psychology, addressing root objections, and ethical closing.": "Diagnóstico de marcos de cuestionamiento, psicología de invitación, abordar objeciones de raíz y cierre ético.",
  "The 14-Minute Clarity frame": "El marco de claridad de 14 minutos",
  "Resolving money & time concerns": "El dinero y las preocupaciones de tiempo",
  "Positioning yourself professionally on business media, magnetic content creation, and digital storefront setup.": "Posicionándose profesionalmente en medios de negocios, creación de contenido magnético y configuración digital storefront.",
  "High-trust bio optimization": "Optimización biológica de alta confianza",
  "Attracting business builders": "Atraer a los constructores de empresas",
  "Operating your private True Legacy CRM, managing prospect pipelines, calendar scheduling, and automated nurturing.": "Operando su CRM privado True Legacy, administrando oleoductos, programación de calendarios y crianza automatizada.",
  "Live contact attribution": "Atribución de contacto vivo",
  "Instant lead notifications": "Notificaciones instantáneas de plomo",
  "Custom referral share links": "Enlaces personalizados para compartir referencias",
  "Leadership psychology, team accountability, developing independent trainers, and building resilient culture.": "Psicología del liderazgo, responsabilidad del equipo, desarrollo de capacitadores independientes y construcción de una cultura resiliente.",
  "Duplication frameworks": "Marcos de duplicación",
  "Team meeting facilitation": "Facilitación de las reuniones del equipo",
  "Developing next-gen 6A leaders": "Desarrollo de líderes de próxima generación 6A",
  "Entering emerging markets, local leadership development, cross-border logistics, and international growth strategy.": "Entrar en mercados emergentes, desarrollo de liderazgo local, logística transfronteriza y estrategia de crecimiento internacional.",
  "Emerging market playbooks": "Libros de juegos de mercados emergentes",
  "LATAM & Asian strategies": "LATAM y estrategias asiáticas",
  "Local event organization": "Organización de eventos locales",
  "Weekly live English global masterclasses, LATAM Spanish workshops, live Q&A, and interactive community sessions.": "Clases magistrales globales semanales de inglés en vivo, talleres LATAM en español, preguntas y respuestas en vivo y sesiones comunitarias interactivas.",
  "Weekly Wednesday Global Call": "Miércoles Semanal Llamada Global",
  "LATAM Spanish workshops": "Talleres de español LATAM",
  "Executive leadership briefings": "Reuniones informativas de dirección ejecutiva",
  "Anytime, Anywhere": "En cualquier momento, en cualquier lugar",
  "THE ACADEMY GOES WHERE YOU GO.": "La Academia va a donde tú vas.",
  "Some people learn early in the morning before family commitments. Some study during an evening commute. Others review scripts right before an executive presentation.": "Algunas personas aprenden temprano en la mañana antes de los compromisos familiares. Algunos estudian durante un viaje nocturno. Otros revisan guiones justo antes de una presentación ejecutiva.",
  "Your development should not depend solely on someone else’s calendar. Access high-definition training on demand, resume lessons seamlessly, and combine self-paced mastery with live global calls.": "Su desarrollo no debe depender únicamente del calendario de otra persona. Acceda a la formación de alta definición bajo demanda, reanude las lecciones sin problemas, y combine dominio a su ritmo con llamadas globales en vivo.",
  "Desktop": "Escritorio",
  "Tablet": "Comprimido",
  "Mobile App": "Aplicación móvil",
  "Private Streaming Vault": "Vault de transmisión privada",
  "Optimized 16:9 streaming": "Optimizado 16:9 streaming",
  "Offline guides & slides": "Guías y diapositivas sin conexión",
  "True Legacy Mobile Portal": "Portal móvil verdadero legado",
  "Currently In Progress": "En curso",
  "The PRIME 6™: Prospecting the Right People": "El PRIME 6TM: Prospección de las personas correctas",
  "Next Live Masterclass": "Siguiente Masterclass en vivo",
  "Wed 8:30 PM EST": "Miércoles 8:30 PM EST",
  "Two Integrated Pillars": "Dos pilares integrados",
  "LEARN ON DEMAND. DEVELOP LIVE.": "Aprendan a demandar.",
  "Self-paced education gives you knowledge. Live community interaction gives you execution and confidence.": "La educación a ritmo propio le da conocimiento. La interacción comunitaria en vivo le da ejecución y confianza.",
  "Pillar 01 · On-Demand Academy": "Pilar 01 · Academia en Demand",
  "Learn at Your Own Pace": "Aprende en tu propio Pace",
  "Always available 24/7 on your personal device. Return to core modules whenever you need to prepare for a demonstration or train a new partner.": "Siempre disponible 24/7 en tu dispositivo personal. Regresa a los módulos centrales cuando necesites prepararte para una demostración o entrenar a un nuevo socio.",
  "Private recorded video masterclasses & playbooks": "Clases maestras de vídeo grabadas privadas y libros de jugadas",
  "Downloadable objection handling & invitation scripts": "Manejo de objeciones y scripts de invitación descargables",
  "Product science breakdown & certification archives": "Desglose científico de productos y archivos de certificación",
  "Patent & 8-Point compensation plan video models": "Patentes y modelos de vídeo de plan de compensación de 8 puntos",
  "Private CRM video setup & lead workflow guides": "Configuración privada de vídeo CRM y guías de flujo de trabajo de plomo",
  "Available 24/7/365 for team members": "Disponible las 24 horas del día para los miembros del equipo",
  "Pillar 02 · Live Development": "Pilar 02 · Desarrollo en vivo",
  "Connected to Real Leaders": "Conectado con líderes reales",
  "You are never building in isolation. Join weekly live calls, ask real-time questions, and learn directly from top global builders in English and Spanish.": "Nunca estás construyendo en aislamiento. Únete a llamadas semanales en vivo, haz preguntas en tiempo real y aprende directamente de los principales constructores globales en inglés y español.",
  "Weekly Global Strategy & Leadership Calls (Wednesday)": "Llamamientos semanales de estrategia y liderazgo mundiales (miércoles)",
  "LATAM Spanish expansion workshops & presentations": "LATAM Talleres y presentaciones de expansión española",
  "Live interactive Q&A & pipeline coaching sessions": "Preguntas y respuestas interactivas en vivo y sesiones de entrenamiento de tuberías",
  "Regional summits & in-person team workshops": "Cumbres regionales y talleres en persona",
  "Direct access to senior mentors across 14 markets": "Acceso directo a mentores superiores en 14 mercados",
  "Global English & LATAM Spanish schedules": "Horarios globales de inglés y español LATAM",
  "THE LIBRARY GIVES YOU INFORMATION.": "La biblioteca te da información.",
  "THE COMMUNITY HELPS YOU APPLY IT.": "La comunidad te ayuda a aplicarlo.",
  "Field-Tested Leadership": "Liderazgo ensayado sobre el terreno",
  "TRAINING SHOULD COME FROM EXPERIENCE, NOT THEORY ALONE.": "El entrenamiento debe venir de la experiencia, no de la teoría sola.",
  "Every module, script, and workshop in True Legacy Academy is authored and led by distributors actively building international organizations today.": "Cada módulo, guión y taller de True Legacy Academy está escrito y dirigido por distribuidores que actualmente construyen activamente organizaciones internacionales.",
  "Teaching Area:": "Área de enseñanza:",
  "Global & LATAM Strategy · Systems & CRM": "Estrategia global y LATAM · Sistemas y CRM",
  "Pioneering emerging markets, architecting digital tools, and leading bilingual team expansion.": "Pionero en mercados emergentes, arquitectura de herramientas digitales y liderazgo en la expansión del equipo bilingüe.",
  "Active True Legacy Trainer": "Entrenador activo del verdadero legado",
  "Relationship Building · Authentic Storytelling": "Construcción de relaciones · Authentic Storytelling",
  "Guiding leaders across the U.S. and Latin America with values-aligned leadership.": "Guía a líderes en Estados Unidos y América Latina con liderazgo alineado con valores.",
  "Global Compensation Mastery · Asian & Middle East Markets": "Maestría en Compensación Global · Mercados de Asia y Medio Oriente",
  "Accountant by training, international builder spanning Malaysia, UAE, Türkiye, and India.": "Contador por formación, constructor internacional que abarca Malasia, Emiratos Árabes Unidos, Türkiye y la India.",
  "Structural Legacy · Team Duplication": "Legado estructural · Duplicación del equipo",
  "Built from the ground up, developing generational discipline and long-term organization stability.": "Construido desde cero, desarrollando la disciplina generacional y la estabilidad de la organización a largo plazo.",
  "True Legacy Leader": "Verdadero líder del legado",
  "High-Performance Mindset · Executive Leadership": "Mentes de alto rendimiento · Liderazgo ejecutivo",
  "Over a decade coaching elite performers, corporate executives, and top athletes.": "Más de una década entrenando a artistas de élite, ejecutivos corporativos y atletas destacados.",
  "Community Building · Disciplined Execution": "Edificio comunitario · Ejecución disciplinada",
  "Former athlete and entrepreneur building community and family legacy in Los Angeles.": "Ex atleta y empresario construyendo legado comunitario y familiar en Los Ángeles.",
  "Health & Wellness Marketing · 35+ Years Experience": "Marketing en Salud y Bienestar · 35+ Años de Experiencia",
  "Over 35 years in the supplement industry, passionate about physical and financial health.": "Más de 35 años en la industria de suplementos, apasionado por la salud física y financiera.",
  "Global Cross-Border Distribution · Equity & Purpose": "Distribución transfronteriza global · Equidad y propósito",
  "Former equity trader building international distribution across Dubai, Singapore, and Türkiye.": "Excomerciante de capital que construye distribución internacional en Dubai, Singapur y Türkiye.",
  "Strategic Alignment": "Alineación estratégica",
  "A GREAT COMPANY IS EVEN MORE POWERFUL WHEN YOU KNOW HOW TO LEVERAGE THE OPPORTUNITY.": "Una compañía genial es aún más poderosa cuando sabes cómo aprovechar la oportunidad.",
  "Enagic brings 50+ years of Japanese manufacturing excellence, medical device certifications, and a global distribution infrastructure. True Legacy does not replace Enagic—we equip independent distributors with the education and tools needed to build responsibly.": "Enágic aporta más de 50 años de excelencia en la fabricación japonesa, certificaciones de dispositivos médicos y una infraestructura de distribución global. True Legacy no reemplaza a Enágic: equipamos a distribuidores independientes con la educación y las herramientas necesarias para construir responsablemente.",
  "The Global Vehicle": "El vehículo mundial",
  "Patented Medical Ionizers": "Ionizadores médicos patentados",
  "Global Branch Infrastructure": "Infraestructura de la Subdivisión Mundial",
  "TRUE LEGACY": "LEGACIÓN VERDADERA",
  "The Development System": "El sistema de desarrollo",
  "Structured Academy Education": "Educación académica estructurada",
  "Private CRM & Lead Pipeline": "CRM privado y tubería de plomo",
  "Mentorship & Duplication": "Mentoría y duplicación",
  "Emerging Market Strategy": "Estrategia de mercados emergentes",
  "THE RESULT": "EL RESULTADO",
  "A Prepared Distributor": "Un distribuidor preparado",
  "Clear Step-by-Step Roadmap": "Hoja de ruta clara paso a paso",
  "High-Confidence Presenting": "Presentación de alta confianza",
  "Active Team Support": "Apoyo activo al equipo",
  "Long-Term Sustainability": "Sostenibilidad a largo plazo",
  "Unbundled Value": "Valor desagregado",
  "WHAT WOULD THIS EDUCATION COST ON ITS OWN?": "¿Qué costaría esta educación por su cuenta?",
  "In traditional entrepreneurship, builders pay thousands of dollars separately for sales training, executive coaching, CRM software, branding courses, and mastermind memberships.": "En el emprendimiento tradicional, los constructores pagan miles de dólares por separado para capacitación en ventas, entrenamiento ejecutivo, software de CRM, cursos de marca y membresías de cerebros.",
  "Sales & Closing Training": "Capacitación en ventas y cierre",
  "Executive Leadership Coaching": "Coaching de liderazgo ejecutivo",
  "Custom CRM & Pipeline Software": "Software personalizado de CRM y tubería",
  "Personal Branding & Media Strategy": "Estrategia de marca y medios personales",
  "Product Science & Tech Demos": "Ciencia de productos y tecnología Demos",
  "Emerging Market Expansion Playbooks": "Libros de juegos de expansión del mercado emergente",
  "Weekly Masterclasses & Live Q&A": "Clases magistrales semanales y preguntas y respuestas en vivo",
  "Downloadable Script Vaults": "Bóvedas de script descargables",
  "Global Peer Community": "Comunidad internacional de homólogos",
  "Included Access": "Acceso incluido",
  "TRUE LEGACY ACADEMY": "ACADEMIA VERDADERA DE LA LEGIA",
  "Included at no additional cost for eligible independent distributors who choose to build directly with the True Legacy organization.": "Incluido sin costo adicional para los distribuidores independientes elegibles que deciden construir directamente con la organización True Legacy.",
  "Because we believe developing people is how you develop markets.": "Porque creemos que desarrollar personas es como desarrollar mercados.",
  "Authenticity & Compliance": "Autenticidad y cumplimiento",
  "NO HYPE. NO MAGIC BUTTON.": "No hay presión, no hay botón mágico.",
  "True Legacy does not promote unrealistic shortcuts. Building a successful independent business requires genuine dedication, skill development, and consistent effort.": "True Legacy no promueve atajos poco realistas. Construir un negocio independiente exitoso requiere dedicación genuina, desarrollo de habilidades y esfuerzo consistente.",
  "No Guarantees": "Sin garantías",
  "The Academy cannot guarantee income, rank, or individual results. Your business outcome depends on your execution.": "La Academia no puede garantizar ingresos, rango o resultados individuales. Su resultado de negocio depende de su ejecución.",
  "Real Capability": "Capacidad real",
  "What we do provide is the clearest environment, proven frameworks, live examples, and tools to master the profession.": "Lo que proporcionamos es el entorno más claro, marcos probados, ejemplos en vivo y herramientas para dominar la profesión.",
  "Independent Accountability": "Responsabilidad independiente",
  "You remain an independent business owner operating with full compliance, respect for Enagic policies, and personal ethics.": "Usted sigue siendo un dueño de negocio independiente que opera con pleno cumplimiento, respeto a las políticas Enágicas y ética personal.",
  "WE PROVIDE THE ENVIRONMENT. YOU PROVIDE THE EFFORT.": "Proveemos el medio ambiente.",
  "Real Transformation": "Transformación real",
  "FROM “I DON’T KNOW HOW” TO “LET ME SHOW YOU.”": "DE “NO SE CÓMO” A “DEJAME QUE TE MUESTRE”.",
  "Real growth happens when uncertainty is replaced by understanding and structured repetition.": "El crecimiento real ocurre cuando la incertidumbre es reemplazada por la comprensión y la repetición estructurada.",
  "First Demonstration Conducted": "Primera demostración realizada",
  "Overcoming Presentation Anxiety": "Superar la ansiedad de presentación",
  "Before Academy:": "Antes de la Academia:",
  "“I was afraid of speaking about medical water or getting technical questions I couldn’t answer.”": "“Tenía miedo de hablar de agua médica o de recibir preguntas técnicas que no podía responder”.",
  "With True Legacy:": "Con verdadero legado:",
  "“With the standardized video demonstrations and clear script outlines, I let the tools do the talking with total confidence.”": "“Con las demostraciones de video estandarizadas y los esquemas claros del guión, dejo que las herramientas hablen con total confianza”.",
  "Skill Capability Milestone": "Hito de habilidad",
  "Daily System Activated": "Sistema diario",
  "Structuring a Real Daily Pipeline": "Cómo estructurar un flujo diario real de prospectos",
  "“I had random contacts scattered across sticky notes and didn’t know who to follow up with.”": "“Tenía contactos aleatorios dispersos en notas adhesivas y no sabía con quién seguir.”",
  "“The True Legacy CRM automated my reminders and gave me a clear 20-minute daily method of operation.”": "“El CRM de True Legacy automatizó mis recordatorios y me dio un método de operación diario claro de 20 minutos.”",
  "First Duplication Achieved": "Primera duplicación lograda",
  "Onboarding New Team Partners": "Incorporación de nuevos socios del equipo",
  "“I was terrified of enrolling someone because I thought I would have to teach them everything myself.”": "“Estaba aterrorizada de inscribir a alguien porque pensé que tendría que enseñarle todo yo mismo”.",
  "“I plugged them straight into the 6-Week Academy Roadmap, and they began learning from senior leaders immediately.”": "“Los enchufé directamente a la Hoja de Ruta de la Academia de 6 Semanas, y empezaron a aprender de los líderes mayores inmediatamente”.",
  "The True Legacy Vision": "La verdadera visión del legado",
  "THE GOAL ISN’T TO KEEP YOU DEPENDENT ON US.": "El objetivo no es mantenerte deprimido en nosotros.",
  "THE GOAL IS TO DEVELOP YOU UNTIL SOMEONE ELSE CAN DEPEND ON YOU.": "La meta es desarrollarte hasta que alguien más pueda decretarte.",
  "Sustainable global organizations are never built by one superstar. They are built by empowered, independent leaders who develop more leaders.": "Las organizaciones globales sostenibles nunca son construidas por una superestrella. Son construidas por líderes independientes empoderados que desarrollan más líderes.",
  "Learn the technologies. Master the business. Refine your communication. Build confidence. Step into leadership. Then help the next person do the same. That is how communities expand, how markets grow, and how true legacy is built.": "Aprenda las tecnologías. Domine el negocio. Refine su comunicación. Cree confianza. Acceda al liderazgo. Luego ayude a la siguiente persona a hacer lo mismo. Así es como las comunidades se expanden, cómo crecen los mercados y cómo se construye un verdadero legado.",
  "STUDENT": "ESTUDIANTE",
  "Absorb the fundamentals": "Absorbe los fundamentos",
  "BUILDER": "CONSTRUCCIÓN",
  "Execute daily activity": "Ejecutar actividad diaria",
  "Guide and support others": "Guía y apoyo a otros",
  "Duplicate the system": "Duplicar el sistema",
  "YOU BRING THE AMBITION.": "Traiga la ambición.",
  "WE’LL BRING THE ENVIRONMENT TO DEVELOP IT.": "Vamos a traer el medio ambiente para desarrollarlo.",
  "When you choose to build with True Legacy, you are entering an international community committed to education, leadership, systems, and long-term development.": "Cuando eliges construir con True Legacy, estás entrando en una comunidad internacional comprometida con la educación, el liderazgo, los sistemas y el desarrollo a largo plazo.",
  "Explore the True Legacy Opportunity": "Explore la oportunidad del verdadero legado",
  "True Legacy Academy is an independent distributor training resource. Enagic® is a registered trademark of Enagic Co., Ltd. True Legacy operates independently. No earnings or rank outcomes are guaranteed.": "True Legacy Academy es un recurso de capacitación para distribuidores independientes. Enagic® es una marca registrada de Enagic Co., Ltd. True Legacy opera de forma independiente. No se garantizan ingresos ni resultados de rango.",
  "True Legacy Duo": "Duo verdadero legado",
  "True Legacy World": "El verdadero mundo del legado",
  "True Legacy LATAM": "Verdadero legado LATAM",
  "True Legacy World.": "Verdadero Mundo Legado.",
  "Install True Legacy": "Instalar un verdadero legado",
  "Open your dashboard and training from your home screen.": "Abra su tablero y entrenamiento desde su pantalla de inicio.",
  "Install": "Instalar",
  "Toggle menu": "Conmutar menú",
  "Search syllabus topics...": "Buscar temas de syllabus...",
  "United States": "Estados Unidos",
  "Morocco": "Marruecos",
  "Brazil": "Brasil",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  "Malaysia": "Malasia",
  "Turkey": "Turquía",
  "Spain": "España",
  "European Union": "Unión Europea",
  "Legal": "Jurídico",
  "Install True Legacy app": "Instalar la aplicación True Legacy",
  "Dismiss install invitation": "Desestimar invitación de instalación",
  "Back to top": "Volver al principio"
})
