// Generated from exact text that remained English when the Spanish locale was active.
// Keep brand names and product specifications unchanged when reviewing updates.
export const SpanishLegacyBusiness: Readonly<Record<string, string>> = Object.freeze({
  "173 Countries": "173 países",
  "52+ Years Enagic": "Más de 52 años de Enagic",
  "6A IS A MILESTONE.": "6A ES UN HITO.",
  "True Legacy Business | Mehdi Cohen": "Negocio True Legacy | Mehdi Cohen",
  "Presented by": "Presentado por",
  "Talk to": "Hablar con",
  "THE TRUE LEGACY BUSINESS": "EL NEGOCIO TRUE LEGACY",
  "TWO PRODUCTS.": "Dos productos.",
  "ONE BUSINESS STRATEGY.": "Una estrategia de negocios.",
  "A SYSTEM BUILT TO SCALE.": "Un sistema a escala.",
  "Build around two distinct product conversations, a progressive commission structure, and a proven training ecosystem designed to help entrepreneurs learn, share and duplicate what works.": "Construir alrededor de dos conversaciones de productos diferentes, una estructura de comisión progresiva, y un ecosistema de entrenamiento probado diseñado para ayudar a los empresarios a aprender, compartir y duplicar lo que funciona.",
  "SEE HOW IT WORKS": "Ver cómo funciona",
  "WATCH THE PRESENTATION": "VER LA PRESENTACIÓN",
  "TALK TO": "HABLA A",
  "Established": "Establecida",
  "Global Reach": "Alcance mundial",
  "Flagship Focus": "Foco emblemático",
  "Premium Hardware": "Hardware premium",
  "Infrastructure": "Infraestructura",
  "Training + Systems": "Formación + Sistemas",
  "COMPLETE EXECUTIVE OVERVIEW": "RESEÑA COMPLETA EJECUTIVA",
  "SEE THE FULL PICTURE.": "Ver la foto completa.",
  "OFFICIAL BUSINESS PRESENTATION.": "PRESENTACIÓN OFICIAL DE EMPRESAS.",
  "Watch the comprehensive True Legacy business presentation explaining product synergy, the patented 8-point compensation system, and our duplication roadmap.": "Vea la completa presentación empresarial True Legacy explicando la sinergia del producto, el sistema patentado de compensación de 8 puntos y nuestra hoja de ruta de duplicación.",
  "Verified True Legacy Executive Briefing": "Informe Ejecutivo Verificado Verdadero Legado",
  "Official Curriculum · Presented by Team Leadership": "Currículo Oficial · Presentado por Liderazgo de Equipo",
  "ON WHATSAPP": "¿Qué pasa?",
  "BOOK A STRATEGY CALL": "RESERVA UNA LLAMADA A LA ESTRATEGIA",
  "START HERE": "Empieza aquí.",
  "WHAT ARE YOU": "¿Qué eres?",
  "ACTUALLY BUILDING?": "¿De verdad?",
  "At its core, the business model is clean, direct, and straightforward.": "En esencia, el modelo de negocio es limpio, directo y directo.",
  "You introduce people to premium Enagic wellness and environmental technologies that households and businesses use every day.": "Presentas a la gente a las tecnologías ambientales y de bienestar Enágico premium que los hogares y las empresas utilizan todos los días.",
  "When qualifying sales are made, Enagic's patented direct-sales compensation structure generates upfront commissions.": "Cuando se realizan ventas elegibles, la estructura patentada de Enagic de compensación de ventas directas genera comisiones iniciales.",
  "As your cumulative business advances through the rank structure, the commission value associated with future qualifying direct sales increases significantly.": "A medida que su negocio acumulado avanza a través de la estructura de rango, el valor de la comisión asociada con futuras ventas directas calificativas aumenta significativamente.",
  "The Core Progression Loop": "La parte central de la progresión",
  "SHARE": "COMPARTIR",
  "SALE": "VENTA",
  "POINTS": "PUNTOS",
  "LEADERSHIP": "LÍDERES",
  "Every step builds cumulative enterprise value. No starting over each month.": "Cada paso genera un valor empresarial acumulativo.",
  "Global Enterprise Infrastructure": "Infraestructura empresarial mundial",
  "Building an independent, asset-backed global distribution business with Leveluk K8 and emGuarde across 170+ countries.": "Crear un negocio de distribución global independiente y respaldado por activos con Leveluk K8 y EmGuarde en más de 170 países.",
  "THE FOUNDATION": "LA FUNDACIÓN",
  "TWO DISTINCT CONVERSATIONS.": "Dos conversaciones distintas.",
  "Rather than pitching a sprawling product catalog, True Legacy focuses the business front door on two world-class flagship technologies.": "En lugar de lanzar un extenso catálogo de productos, True Legacy enfoca la puerta principal del negocio en dos tecnologías emblemáticas de clase mundial.",
  "WATER & CELLULAR HEALTH": "AGUA Y SALUD CELULAR",
  "FLAGSHIP IONIZATION": "IONERIZACIÓN DE LUGARES",
  "Enagic® 8-Plate Medical Ionization System": "Sistema de ionización médica Enagic® de 8 placas",
  "A premium Japanese water-ionization system built around something every household and business already consumes every single day: water. Generates 5 distinct functional water grades, active molecular hydrogen (H2), and powerful antioxidant potential.": "Un sistema de ionización de agua japonés de primera calidad construido alrededor de algo que cada hogar y negocio ya consume cada día: agua. Genera 5 grados de agua funcionales diferentes, hidrógeno molecular activo (H2), y potente potencial antioxidante.",
  "Compensation Value": "Valor de compensación",
  "/ COMMISSION POINT": "COMISIÓN",
  "Base retail: $5,890 + tax · 8 commission points allocated per machine.": "Retail base: $5,890 + impuesto · 8 puntos de comisión asignados por máquina.",
  "Explore Kangen Water": "Explore el agua de Kangen",
  "CONVERSATION 01": "CONVERSACIÓN 01",
  "ENVIRONMENTAL HARMONIZATION": "HARMONIZACIÓN AMBIENTAL",
  "PATENTED RESONANCE": "RESPONSABILIDAD ATENIDA",
  "Patented 360° Electromagnetic Harmonizer": "Patentado 360° electromagnético armonizador",
  "A second product category creating an entirely different conversation around today's increasingly connected environments. Harmonizes electromagnetic noise across a 3-meter radius without interfering with telecommunications or WiFi connectivity.": "Una segunda categoría de producto creando una conversación completamente diferente en torno a los entornos cada vez más conectados de hoy en día. Armoniza el ruido electromagnético a través de un radio de 3 metros sin interferir con las telecomunicaciones o la conectividad WiFi.",
  "Base retail: $2,880 + tax · 8 commission points allocated per set.": "Base minorista: $2,880 + impuesto · 8 puntos de comisión asignados por conjunto.",
  "Explore emGuarde": "Explorar emGuarde",
  "CONVERSATION 02": "CONVERSACIÓN 02",
  "THE COMPENSATION STRUCTURE": "LA ESTRUCTURA DE INDEMNIZACIÓN",
  "ONE POINT.": "Un punto.",
  "MORE VALUE AS YOU PROGRESS.": "Más valor que tú.",
  "The commission value associated with a qualifying direct sale increases as you advance through the rank structure.": "El valor de la comisión asociada a una venta directa calificada aumenta a medida que avanzas a través de la estructura de rango.",
  "Selected Model:": "Modelo seleccionado:",
  "Official Retail Price:": "Precio oficial al por menor:",
  "$5,890 + applicable taxes": "$5,890 + impuestos aplicables",
  "Commission Base Per Point": "Base de la Comisión por punto",
  "Per direct sale in this lane": "Por venta directa en este lane",
  "PATENTED IN JAPAN & GLOBALLY": "EN JAPÓN Y GLOBAL",
  "The 8-Point Global Patented Commission System": "El sistema de Comisión Mundial Patentada de 8 puntos",
  "When a product is sold, Enagic allocates a dedicated marketing pre-budget of exactly 8 points distributed out equally to qualifying distributors. No traditional advertising budgets. The distributor is the distribution channel.": "Cuando un producto se vende, Enágic asigna un pre-presupuesto de marketing dedicado de exactamente 8 puntos distribuidos por igual a los distribuidores cualificados. No hay presupuestos de publicidad tradicional. El distribuidor es el canal de distribución.",
  "Patent No. 87449502": "Patente No 87449502",
  "Verified Enagic Corporation": "Corporación Enágica Verificada",
  "Cumulative Growth Architecture": "Arquitectura acumulativa del crecimiento",
  "Every direct and indirect group sale advances your organization through permanent rank milestones from 1A to 6A.": "Cada venta directa e indirecta de grupos avanza su organización a través de hitos permanentes de rango de 1A a 6A.",
  "SYSTEMATIC ADVANCEMENT": "ADELANTO SISTEMÁTICO",
  "THE BUSINESS": "El negocio",
  "GROWS IN STAGES.": "Crece en puestos.",
  "You do not need to figure out everything on day one. Enagic's rank structure provides a clear, progressive roadmap from your very first direct sale to enterprise leadership.": "Usted no necesita averiguar todo en el primer día. La estructura de rango de Enágico proporciona una hoja de ruta clara y progresiva desde su primera venta directa a la dirección empresarial.",
  "Sales 1–2": "Ventas 1-2",
  "Stage 0": "Etapa 0",
  "Your starting direct sales position. Establishes your first commission lanes.": "Tu posición inicial de ventas directas. Establece tus primeras líneas de comisión.",
  "Sales 3–10": "Ventas 3-10",
  "Opens your 2-point direct sale lane. Point value multiplies immediately.": "Abre su lane de venta directa de 2 puntos. El valor del punto se multiplica inmediatamente.",
  "Sales 11–20": "Ventas 11-20",
  "Opens your 3-point lane as your cumulative group sales develop.": "Abre su lane de 3 puntos a medida que se desarrollan las ventas de su grupo acumulativo.",
  "Sales 21–50": "Ventas 21–50",
  "Opens your 4-point lane. Cumulative team and direct production advances rank.": "Abre su lana de 4 puntos. Equipo acumulado y la producción directa avanza rango.",
  "Sales 51–100": "Ventas 51–100",
  "Opens your 5-point lane. Senior distributor leadership tier.": "Abre tu lane de 5 puntos.",
  "Flagship leadership milestone. Unlocks 6-point direct lanes and executive development bonuses.": "Marcado hito de liderazgo. Desbloquea lanes directas de 6 puntos y bonos de desarrollo ejecutivo.",
  "Expand": "Expandir",
  "Advanced Qualification Details": "Detalles de cualificación avanzada",
  "THE DUO ADVANTAGE": "LA VENTAJA DE DUO",
  "TWO ACCOUNTS. DOUBLE COMMISSIONS.": "Dos cuentas. Comisiones dobles.",
  "FAST TRACK TO 6A.": "RÁPIDO TRACK A 6A.",
  "When you establish a Duo position, you unlock two income accounts from day one. Every Duo sale pays out commissions on": "Al establecer una posición Duo, habilitas dos cuentas de ingresos desde el primer día. Cada venta Duo paga comisiones sobre",
  "both products simultaneously": "ambos productos simultáneamente",
  "and counts as": "y cuenta como",
  "two unit sales": "ventas en dos unidades",
  "toward your rank progression.": "hacia tu progresión de rango.",
  "YOUR ENAGIC DUO POSITION STRUCTURE": "SU ESTRUCTURA ENAGICA DE POSICIÓN DE DUO",
  "How Two Accounts Stack to Double Your Commission on Every Duo Sale": "Cómo se combinan dos cuentas para duplicar tu comisión en cada venta Duo",
  "YOUR 1ST ACCOUNT": "SU PRIMERA CUENTA",
  "Medical Electrolysis Device": "Dispositivo médico de electrólisis",
  "Fixed 1A Position =": "Posición fija 1A =",
  "per Duo sale": "venta por Duo",
  "STACKED POSITION": "POSICIÓN ESTABLECIDA",
  "YOUR 2ND ACCOUNT": "SU SEGUNDA CUENTA",
  "Bio-Resonance EMF Defense": "Defensa del EMF de bioresonancia",
  "Advances 1A–6A =": "Anticipos 1A–6A =",
  "$500 to $3,000": "500 a 3.000 dólares",
  "Combined Duo Commission Point Value": "Valor de punto combinado de la Comisión Duo",
  "$350 (K8) + $150 (emGuarde) =": "350 dólares (K8) + 150 dólares (emGuarde) =",
  "$500 Per Point": "$500 por punto",
  "Every qualifying Duo sale flows through both accounts, generating": "Cada venta Duo cualificada fluye a través de ambas cuentas, generando",
  "$1,000 to $3,500": "1.000 a 3.500 dólares",
  "in net commission.": "en comisión neta.",
  "Double Commission Matrix": "Matriz doble de la Comisión",
  "Fast Track to 6A Roadmap": "Vía rápida a la hoja de ruta 6A",
  "ENAGIC DUO PROGRESSIVE PAYOUT": "ENAGIC DUO PAYOUT PROGRESIVO",
  "Net Commission Per Duo Sale Across Ranks": "Net Commission Per Duo Sale a través de Ranks",
  "Dual Payout: 1st Account ($500) + 2nd Account ($500 to $3,000)": "Pago doble: 1a Cuenta (500 dólares) + 2a Cuenta (500 a 3.000 dólares)",
  "Rank Tier": "Categoría",
  "Direct Sales Milestone": "Milestone de ventas directas",
  "Total Net Commission": "Total Comisión neta",
  "$500 (1 pt)": "500 dólares (1 pt)",
  "per Duo sold": "por Duo vendido",
  "Sales 3–5": "Ventas 3-5",
  "$1,000 (2 pts)": "1.000 dólares (2 puestos)",
  "Sale 6 (11 units)": "Venta 6 (11 unidades)",
  "$1,500 (3 pts)": "1.500 dólares (3 puestos)",
  "Sales 11+ (21 units)": "Ventas 11+ (21 unidades)",
  "Unlocks 4-point lanes": "Desbloquea las lanas de 4 puntos",
  "$2,000 (4 pts)": "2.000 dólares (4 pts)",
  "Sales 26+ (51 units)": "Ventas 26+ (51 unidades)",
  "Senior leadership tier": "Personal directivo superior",
  "$2,500 (5 pts)": "2.500 dólares (5 puestos)",
  "Sales 51+ (101 units)": "Ventas 51+ (101 unidades)",
  "Flagship title qualification": "Título del buque insignia",
  "$3,000 (6 pts)": "3.000 dólares (6 puestos)",
  "THE FIRST 6 DUO SALES MILESTONE": "EL PRIMER 6 DUO S MILESTONA",
  "$8,500 In Net Commissions on Your First 6 Duo Sales.": "$8.500 en comisiones netas en sus primeras 6 ventas Duo.",
  "Because each Duo counts as 2 units, your 6th Duo sale brings your total to 12 units—automatically advancing your second account to": "Debido a que cada Duo cuenta como 2 unidades, su sexta venta de Duo eleva su total a 12 unidades, avanzando automáticamente su segunda cuenta a",
  "Total Upfront Direct Cashflow": "Total inicial Flujo de caja directo",
  "Completely covers your Duo hardware investment": "Cubre completamente su inversión en hardware Duo",
  "View": "Ver",
  "Official True Legacy Presentation Slides": "Presentaciones oficiales del verdadero legado",
  "MULTIPLE ENTRY POINTS": "PUNTOS DE ENTRADA MULTIPLES",
  "MORE THAN": "MÁS QUE",
  "ONE WAY TO CONNECT.": "Una manera de conectar.",
  "Not every person enters through the same door. A single product often limits your audience to people with one specific interest.": "No todas las personas entran por la misma puerta. Un solo producto a menudo limita su audiencia a personas con un interés específico.",
  "The Duo creates multiple natural entry points into the same underlying ecosystem:": "El Duo crea múltiples puntos de entrada naturales en el mismo ecosistema subyacente:",
  "Some people connect with Water": "Algunas personas se conectan con el agua",
  "Health, fitness, longevity, athletic recovery, and kitchen wellness.": "Salud, fitness, longevidad, recuperación atlética y bienestar de la cocina.",
  "Some people connect with Technology & Environment": "Algunas personas se conectan con Tecnología y Medio Ambiente",
  "Connected workspaces, screen fatigue, EMF consciousness, and office defense.": "Espacios de trabajo conectados, fatiga de pantalla, conciencia de EMF y defensa de oficina.",
  "Some people connect with the Business Opportunity": "Algunas personas se conectan con la oportunidad de negocio",
  "Entrepreneurs looking for high-ticket direct sales, global distribution, and leadership duplication.": "Empresarios que buscan ventas directas de alto precio, distribución global y duplicación de liderazgo.",
  "All three doors lead directly into the True Legacy System.": "Las tres puertas conducen directamente al verdadero sistema de legado.",
  "Real weekly leadership masterminds, distributor alignment calls, and global training from anywhere in the world.": "Reales mentes de liderazgo semanales, llamadas de alineación de distribuidores y entrenamiento global desde cualquier parte del mundo.",
  "THE DIFFERENCE": "LA DIFERENCIA",
  "THE PRODUCTS ARE THE VEHICLE.": "Los productos son el vehículo.",
  "THE SYSTEM IS WHAT HELPS YOU BUILD.": "El sistema es lo que te ayuda.",
  "Buying a product and building a business are two completely different things. True Legacy exists to give independent distributors structure, clarity, and duplication around what happens next.": "Comprar un producto y construir un negocio son dos cosas completamente diferentes. True Legacy existe para dar a los distribuidores independientes estructura, claridad y duplicación en torno a lo que sucede a continuación.",
  "INFRASTRUCTURE AT YOUR FINGERTIPS": "INFRAESTRUCTURA EN SUS DEDOS",
  "YOU DON'T START": "No empieces",
  "WITH A BLANK PAGE.": "Con una página en blanco.",
  "Every distributor in True Legacy receives turnkey digital tools, CRM, landing pages, and structured media assets from day one.": "Cada distribuidor en True Legacy recibe herramientas digitales llave en mano, CRM, landing pages y activos de medios estructurados desde el primer día.",
  "YOU": "TÚ",
  "Supported by the True Legacy Operating System": "Apoyado por el verdadero sistema operativo Legado",
  "Academy": "Academia",
  "Step-by-step masterclasses": "Clases maestras paso a paso",
  "Lead CRM": "CRM de plomo",
  "Track prospect engagement": "Seguimiento de la participación",
  "Personal Website": "Sitio web personal",
  "Custom /d/[slug] storefront": "Personalizado /d/[slug] storefront",
  "Product Landers": "Landers de productos",
  "K8, emGuarde, Duo pages": "K8, emGuarde, Duo",
  "Live Webinars": "Webinars vivos",
  "Weekly global presentations": "Presentaciones mundiales semanales",
  "Follow-Up Flows": "Flujos de seguimiento",
  "Automated messaging templates": "Plantillas de mensajería automatizadas",
  "Sales Scripts": "Scripts de ventas",
  "Field-tested objection handling": "Manejo de objeciones sobre el terreno",
  "Call Booking": "Reservación de llamadas",
  "Integrated calendar system": "Sistema de calendario integrado",
  "Multilingual Media": "Medios de comunicación multilingües",
  "EN, ES, FR, PT assets": "Activos de EN, ES, FR, PT",
  "Leadership Dev": "Liderazgo Dev",
  "Mentorship & progression": "Mentoría y progresión",
  "Team Events": "Eventos en equipo",
  "Quarterly global workshops": "Talleres mundiales trimestrales",
  "Market Expansion": "Expansión del mercado",
  "LATAM & emerging markets": "LATAM y mercados emergentes",
  "Learn": "Aprender",
  "Present": "Presente",
  "Follow Up": "Seguimiento",
  "Organize": "Organizar",
  "Duplicate": "Duplicar",
  "LEARN WHILE YOU BUILD": "Aprendan mientras ustedes dominan",
  "A SYSTEM YOU CAN": "UN SISTEMA QUE PUEDE",
  "ACTUALLY FOLLOW.": "Sígueme.",
  "New distributors don't fail because they lack ambition. They fail because they don't know what to say, who to talk to, or how to follow up effectively.": "Los nuevos distribuidores no fallan porque carecen de ambición, porque no saben qué decir, con quién hablar o cómo hacer un seguimiento eficaz.",
  "The True Legacy Academy provides a structured curriculum that covers everything from product science to enterprise team leadership.": "La Academia True Legacy ofrece un plan de estudios estructurado que abarca todo, desde la ciencia del producto hasta el liderazgo del equipo empresarial.",
  "Structured Onboarding": "Incorporación estructurada",
  "Product Education": "Educación sobre productos",
  "Business Fundamentals": "Fundamentos empresariales",
  "Sales Conversations": "Conversaciones de ventas",
  "Field-Tested Scripts": "Scripts probados en campo",
  "Weekly Live Calls": "Llamadas semanales en vivo",
  "PREVIEW THE ACADEMY": "PREVIA LA ACADEMIA",
  "Turnkey Digital Platform": "Plataforma digital llave en mano",
  "Manage your pipeline, training modules, and landing pages on desktop and mobile.": "Gestione su tubería, módulos de capacitación y páginas de aterrizaje en escritorio y móvil.",
  "BEHIND THE SYSTEM": "DENTRO DEL SISTEMA",
  "THIS WASN'T BUILT": "Esto no fue un error.",
  "IN A VACUUM.": "En un vacuum.",
  "True Legacy operates within a larger leadership and training ecosystem that has been developing distributors and sharing experience across international markets for years.": "True Legacy opera dentro de un ecosistema de liderazgo y capacitación más amplio que ha estado desarrollando distribuidores y compartiendo experiencia en los mercados internacionales durante años.",
  "INTERNATIONAL LEADERSHIP SUMMIT · KUALA LUMPUR": "CUMBRE INTERNACIONAL DE LÍDERES · KUALA LUMPUR",
  "TRAIN TOGETHER. BUILD TOGETHER. GROW TOGETHER.": "El tren se junta.",
  "Official True Legacy Leadership Event": "Acto oficial de liderazgo del verdadero legado",
  "Enagic Global Workshop & Leadership Assembly · Malaysia": "Taller Global Enágico & Asamblea de Liderazgo · Malasia",
  "Quarterly gatherings bring leaders and distributors together from across Asia, the Americas, and Europe for in-person masterclasses, strategy alignment, and culture building.": "Las reuniones trimestrales reúnen a líderes y distribuidores de toda Asia, América y Europa para clases magistrales en persona, alineación de estrategias y construcción de cultura.",
  "Real Community · Real Leadership · Real Infrastructure": "Comunidad real · Liderazgo real · Infraestructura real",
  "FULL HOUSE POWER (FHP) KANGEN GROUP · MALAYSIA": "PODER DE LA CASA PLENARIA (FHP)",
  "Attend the Next In-Person Assembly in Kuala Lumpur": "Asistir a la próxima asamblea en persona en Kuala Lumpur",
  "Get full event dates, venue briefings, and workshop curriculum at The Gardens Mall, KL.": "Obtenga las fechas completas del evento, reuniones informativas sobre el lugar y el plan de estudios de los talleres en The Gardens Mall, KL.",
  "ACCESS KUALA LUMPUR EVENT DETAILS": "DETALLES DE EVENTO DE ACCESO KUALA LUMPUR",
  "PROVEN LEADERSHIP": "PROMOVER LA LEY",
  "A SYSTEM SHAPED": "UN SISTEMA COMPETIDO",
  "BY PEOPLE WHO BUILD.": "Por gente a la que le gusta.",
  "This isn't academic theory or textbook sales advice. Every framework inside True Legacy has been forged by distributors who have built organizations across multiple continents.": "Esto no es teoría académica o consejo de ventas de libros de texto. Cada marco dentro de True Legacy ha sido forjado por distribuidores que han construido organizaciones en múltiples continentes.",
  "Real leaders actively presenting in the field": "Líderes reales que se presentan activamente sobre el terreno",
  "Multi-country duplication systems tested over years": "Sistemas de duplicación multinacionales probados a lo largo de los años",
  "Direct mentorship access for emerging distributors": "Acceso directo a mentores para distribuidores emergentes",
  "On-Stage Masterclass Experience": "Experiencia de Masterclass On-Stage",
  "Simon Loh, Ming-Way Sia, Mehdi Cohen, and international leadership training on stage in Kuala Lumpur.": "Simon Loh, Ming-Way Sia, Mehdi Cohen, y entrenamiento internacional de liderazgo en el escenario en Kuala Lumpur.",
  "WHERE TRUE LEGACY SPECIALIZES": "DONDE SE ESPECIALIZA LA LEGIA VERDADERA",
  "BUILD EXISTING MARKETS.": "Mercados existentes de BUILD.",
  "HELP OPEN NEW ONES.": "Ayuda a abrir a las nuevas.",
  "We combine institutional stability with early-mover strategic expansion into under-served territories.": "Combinamos la estabilidad institucional con la expansión estratégica temprana hacia territorios insuficientemente atendidos.",
  "Mature Markets": "Mercados maduros",
  "In established regions like North America and Western Europe, our strategy focuses on fresh branding, digital funnels, modern positioning, and introducing the Duo to revitalize distributor growth.": "En regiones establecidas como Norteamérica y Europa Occidental, nuestra estrategia se centra en el branding fresco, embudos digitales, posicionamiento moderno e introducción del Duo para revitalizar el crecimiento del distribuidor.",
  "Modern positioning replaces outdated network marketing tropes.": "El posicionamiento moderno reemplaza a los tropes de marketing de red obsoletos.",
  "Emerging & LATAM Expansion": "Expansión emergente y LATAM",
  "In developing markets such as Latin America, awareness is still in its early stages. True Legacy develops local leaders early, establishes compliant infrastructure, and creates strategic \"blue ocean\" footholds.": "En el desarrollo de mercados como América Latina, la sensibilización se encuentra todavía en sus primeras etapas. True Legacy desarrolla a los líderes locales temprano, establece una infraestructura compatible y crea puntos de apoyo estratégicos del \"océano azul\".",
  "First-generation leadership development in high-growth territories.": "Desarrollo de liderazgo de primera generación en territorios de alto crecimiento.",
  "THE LONG GAME": "El largo juego",
  "THE GOAL ISN'T": "El objetivo no es",
  "TO NEED YOU FOREVER.": "Para necesitarte para siempre.",
  "A truly scalable organization cannot depend on one person doing everything. If the business collapses when you step away, you haven't built an organization—you've built another job.": "Una organización verdaderamente escalable no puede depender de que una persona haga todo. Si el negocio colapsa cuando te alejas, no has construido una organización, has construido otro trabajo.",
  "The objective is to master a simple system well enough that others can learn it, execute it, and eventually teach it to their own teams.": "El objetivo es dominar un sistema simple lo suficientemente bien como para que otros lo aprendan, lo ejecuten y, finalmente, lo enseñen a sus propios equipos.",
  "The Duplication Lifecycle": "El ciclo de vida de la duplicación",
  "LEARN": "APRENDER",
  "TEACH": "ENSEÑANZA",
  "LEAD": "LÍNEA",
  "Real Leadership Duplication in the Field": "Duplicación real del liderazgo en el campo",
  "Jesse Schexnayder and leaders in executive strategy session with Ming-Way Sia mapping the 6A executive roadmap in Kuala Lumpur.": "Jesse Schexnayder y líderes en sesión de estrategia ejecutiva con Ming-Way Sia mapeando la hoja de ruta ejecutiva 6A en Kuala Lumpur.",
  "ADVANCED HORIZONS": "HORIZONES AVANCEADOS",
  "NOT THE FINISH LINE.": "No la línea final.",
  "Reaching 101 group sales (6A) is just the entrance to executive team development. At advanced levels, the business focuses on developing other 6A leaders within your organization.": "Llegar a 101 ventas grupales (6A) es sólo la entrada al desarrollo del equipo ejecutivo. A niveles avanzados, el negocio se centra en desarrollar otros líderes 6A dentro de su organización.",
  "Foundation": "Fundación",
  "Leadership": "Liderazgo",
  "Developing two distinct 6A leaders in separate branches.": "Desarrollo de dos líderes 6A distintos en ramas separadas.",
  "Duplication": "Duplicación",
  "Second-generation leadership development and depth.": "Desarrollo y profundidad del liderazgo de segunda generación.",
  "Legacy Bonusing": "Bono legado",
  "Enagic global legacy monthly leadership bonuses.": "Enágico global legado mensual bonos de liderazgo.",
  "CANDID ALIGNMENT": "CANDIDATO",
  "THIS IS A BUSINESS.": "Esto es un negocio.",
  "NOT A LOTTERY TICKET.": "No hay mucho para el año 1.",
  "We protect our team culture and focus our energy on partners who possess genuine entrepreneurial discipline.": "Protegemos la cultura de nuestro equipo y centramos nuestra energía en socios que poseen una verdadera disciplina empresarial.",
  "This Is For You If:": "Esto es para usted si:",
  "You are willing to learn a proven communication and sales system.": "Usted está dispuesto a aprender un sistema probado de comunicación y ventas.",
  "You genuinely respect premium, Japanese-engineered wellness hardware.": "Realmente respetas el hardware de bienestar de alta calidad de ingeniería japonesa.",
  "You enjoy building relationships and speaking with other professionals.": "Disfrutas construyendo relaciones y hablando con otros profesionales.",
  "You have a long-term, multi-year asset-building mindset.": "Tienes una mentalidad de creación de activos a largo plazo y multianual.",
  "You want to develop as a public speaker, coach, and community leader.": "Quieres desarrollarte como orador público, entrenador y líder comunitario.",
  "This Is NOT For You If:": "Esto NO ES PARA USTED SI:",
  "You are looking for guaranteed or overnight get-rich-quick income.": "Buscas ingresos garantizados o enriquecerte rápidamente de la noche a la mañana.",
  "You expect completely passive income without putting in initial sales work.": "Usted espera ingresos completamente pasivos sin poner en el trabajo inicial de ventas.",
  "You are unwilling to communicate or follow up with interested prospects.": "Usted no está dispuesto a comunicarse o hacer un seguimiento con las perspectivas interesadas.",
  "You resist following an established duplication framework.": "Se resisten a seguir un marco de duplicación establecido.",
  "Quiet Purpose & Time Freedom": "Propósito tranquilo y libertad temporal",
  "The ultimate goal is building enterprise equity that gives you choice, direction, and long-term autonomy.": "El objetivo final es crear equidad empresarial que le dé elección, dirección y autonomía a largo plazo.",
  "YOUR VERIFIED GUIDE": "SU GUÍA DE VERIF",
  "BUSINESSES ARE BUILT": "LAS NEGOCIACIONES SON B UILT",
  "THROUGH PEOPLE.": "A través de la gente.",
  "Active": "Activo",
  "Independent Enagic® Distributor · True Legacy Leadership": "Distribuidor independiente Enágic® · Liderazgo verdadero legado",
  "Have a candid conversation with": "Tener una conversación franca con",
  "about the products, the Duo strategy, the compensation structure, and what building with True Legacy looks like in your market.": "sobre los productos, la estrategia Duo, la estructura de compensación y cómo es desarrollar con True Legacy en tu mercado.",
  "Book Strategy Call": "Llamada de estrategia del libro",
  "Share": "Compartir",
  "YOUR NEXT MOVE": "TU PRÓXIMA MOVIMIENTO",
  "YOU'VE SEEN WHAT WE BUILD.": "Ya has visto lo que tenemos.",
  "NOW DECIDE IF IT FITS YOU.": "Ahora, si te pega.",
  "Two products. A progressive business model. A system. A team. A path to develop as a leader.": "Dos productos. Un modelo de negocio progresivo. Un sistema. Un equipo. Un camino para desarrollarse como líder.",
  "Compliance Notice:": "Notificación de cumplimiento:",
  "This page is presented by an Independent Enagic® Distributor. True Legacy is an independent distributor community and training ecosystem, not an official corporate entity of Enagic Co., Ltd.": "Esta página es presentada por un Distribuidor Independent Enagic®. True Legacy es una comunidad de distribuidores independientes y un ecosistema de formación, no una entidad corporativa oficial de Enagic Co., Ltd.",
  "Compensation illustrations shown above are mathematical examples based on Enagic's patented 8-point commission plan and do not constitute income guarantees. Actual distributor earnings vary based on individual effort, sales volume, leadership skill, market conditions, and compliance with company policies.": "Las ilustraciones de compensación anteriores son ejemplos matemáticos basados en el plan patentado de comisiones de 8 puntos de Enagic y no constituyen garantías de ingresos. Los ingresos reales de cada distribuidor varían según el esfuerzo individual, el volumen de ventas, la capacidad de liderazgo, las condiciones del mercado y el cumplimiento de las políticas de la compañía.",
  "True Legacy Duo": "Duo verdadero legado",
  "True Legacy World": "El verdadero mundo del legado",
  "True Legacy LATAM": "Verdadero legado LATAM",
  "True Legacy World.": "Verdadero Mundo Legado.",
  "Go back": "Regresa",
  "Share page": "Compartir página",
  "United States": "Estados Unidos",
  "Morocco": "Marruecos",
  "Brazil": "Brasil",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  "Malaysia": "Malasia",
  "Turkey": "Turquía",
  "Spain": "España",
  "European Union": "Unión Europea",
  "Legal": "Jurídico",
  "Back to top": "Volver al principio"
})
