import { SEO } from '@/components/SEO'
import { crmConfigured, crmSupabase, getCrmDistributors, getCrmMembership } from '@/lib/crm'
import type { CrmDistributor, CrmMembership } from '@/lib/crm'
import type { Session } from '@supabase/supabase-js'
import { ArrowLeft, BarChart3, Copy, ExternalLink, Eye, FileText, Heart, Search, Share2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

type Resource = { id: string; title: Record<string,string>; description: Record<string,string>; category: string; resource_type: string; destination_path: string; form_id: string|null; position: number }
type EventRow = { resource_id: string; event_name: string }

export default function AppResourcesPage(){
  const [session,setSession]=useState<Session|null>(null); const [membership,setMembership]=useState<CrmMembership|null>(null); const [distributor,setDistributor]=useState<CrmDistributor|null>(null)
  const [resources,setResources]=useState<Resource[]>([]); const [favorites,setFavorites]=useState<Set<string>>(new Set()); const [events,setEvents]=useState<EventRow[]>([]); const [query,setQuery]=useState(''); const [copied,setCopied]=useState(''); const [loading,setLoading]=useState(crmConfigured)
  useEffect(()=>{if(!crmSupabase)return;crmSupabase.auth.getSession().then(({data})=>{setSession(data.session);if(!data.session)setLoading(false)});const {data}=crmSupabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[])
  useEffect(()=>{if(!session||!crmSupabase)return;let current=true;(async()=>{try{const member=await getCrmMembership(session.user.id);if(!current)return;setMembership(member);if(!member?.active)return;const [ds,rs,fs,es]=await Promise.all([getCrmDistributors(),crmSupabase!.from('crm_resources').select('*').eq('active',true).order('position'),crmSupabase!.from('crm_resource_favorites').select('resource_id').eq('user_id',session.user.id),crmSupabase!.from('crm_resource_events').select('resource_id,event_name').limit(5000)]);if(!current)return;setDistributor(ds.find(d=>d.id===member.distributor_id)||ds.find(d=>d.slug==='mehdi-cohen')||null);setResources((rs.data||[]) as Resource[]);setFavorites(new Set((fs.data||[]).map(row=>row.resource_id)));setEvents((es.data||[]) as EventRow[])}finally{if(current)setLoading(false)}})();return()=>{current=false}},[session])
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return resources.filter(r=>!q||`${r.title.en} ${r.description.en} ${r.category}`.toLowerCase().includes(q))},[query,resources])
  const toggleFavorite=async(resourceId:string)=>{if(!session||!crmSupabase)return;const next=new Set(favorites);if(next.has(resourceId)){await crmSupabase.from('crm_resource_favorites').delete().eq('user_id',session.user.id).eq('resource_id',resourceId);next.delete(resourceId)}else{await crmSupabase.from('crm_resource_favorites').insert({user_id:session.user.id,resource_id:resourceId});next.add(resourceId)}setFavorites(next)}
  const share=async(resource:Resource)=>{if(!distributor||!crmSupabase)return;const url=`${window.location.origin}/resource/${resource.id}/${distributor.slug}`;await navigator.clipboard.writeText(url);setCopied(resource.id);window.setTimeout(()=>setCopied(''),1400);crmSupabase.rpc('crm_record_resource_event',{p_resource_id:resource.id,p_slug:distributor.slug,p_event_name:'share',p_locale:'en',p_metadata:{surface:'resource_library'}}).then(()=>undefined)}
  if(!crmConfigured)return <Gate title="Resource connection required"/>;if(loading)return <main className="min-h-screen bg-[#05091a]"/>;if(!session)return <Gate title="Distributor login required" action={<Link to="/crm" className="rounded-xl bg-cyan-400 px-5 py-3 font-black text-slate-950">Sign in</Link>}/>;if(!membership?.active)return <Gate title="Account not authorized"/>
  return <main className="min-h-screen bg-[#05091a] px-4 pb-32 pt-7 text-white sm:px-6"><SEO title="Shareable Resources | True Legacy" description="Approved, trackable True Legacy resources." noIndex/><div className="mx-auto max-w-7xl"><header className="flex items-center gap-4"><Link to="/app/library" className="grid h-11 w-11 place-items-center rounded-full border border-white/10" aria-label="Back"><ArrowLeft/></Link><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Approved sharing</p><h1 className="text-3xl font-black">Resource Center</h1></div></header>
  <section className="mt-7 rounded-[28px] border border-cyan-300/15 bg-gradient-to-br from-cyan-400/[.1] to-blue-500/[.04] p-6 sm:p-8"><h2 className="text-3xl font-black sm:text-4xl">Share with confidence. See what works.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300">Every link is personalized to your distributor profile and records views, calls to action, and attributed inquiry forms.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric icon={<Share2/>} value={events.filter(e=>e.event_name==='share').length} label="Shares"/><Metric icon={<Eye/>} value={events.filter(e=>e.event_name==='view').length} label="Views"/><Metric icon={<BarChart3/>} value={events.filter(e=>e.event_name==='form_submit').length} label="Leads generated"/></div></section>
  <section className="mt-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">{resources.length} approved resources</p><h2 className="mt-2 text-2xl font-black">True Legacy library</h2></div><label className="flex h-12 items-center gap-3 rounded-xl border border-white/10 bg-white/[.03] px-4 sm:w-80"><Search className="h-4 w-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resources" className="w-full bg-transparent text-sm outline-none"/></label></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(resource=>{const views=events.filter(e=>e.resource_id===resource.id&&e.event_name==='view').length;return <article key={resource.id} className="flex min-h-72 flex-col rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><FileText/></span><button onClick={()=>toggleFavorite(resource.id)} aria-label={favorites.has(resource.id)?'Remove favorite':'Add favorite'} className={favorites.has(resource.id)?'text-rose-300':'text-slate-600'}><Heart className="h-5 w-5" fill={favorites.has(resource.id)?'currentColor':'none'}/></button></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-slate-500">{resource.category}</p><h3 className="mt-2 text-xl font-black">{resource.title.en}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{resource.description.en}</p><p className="mt-4 text-xs text-slate-500">{views} tracked view{views===1?'':'s'}</p><div className="mt-auto grid grid-cols-2 gap-2 border-t border-white/[.07] pt-5"><button onClick={()=>share(resource)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-cyan-400 px-3 text-sm font-black text-slate-950"><Copy className="h-4 w-4"/>{copied===resource.id?'Copied':'Copy link'}</button><a href={`/resource/${resource.id}/${distributor?.slug||''}`} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/10 text-sm font-bold">Preview <ExternalLink className="h-4 w-4"/></a></div></article>})}</div></section></div></main>
}
function Metric({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div className="rounded-2xl border border-white/10 bg-black/15 p-4"><span className="text-cyan-300">{icon}</span><p className="mt-3 text-2xl font-black">{value}</p><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p></div>}
function Gate({title,action}:{title:string;action?:React.ReactNode}){return <main className="grid min-h-screen place-items-center bg-[#05091a] p-5 text-white"><div className="text-center"><h1 className="text-3xl font-black">{title}</h1>{action?<div className="mt-6">{action}</div>:null}</div></main>}
