import { SEO } from '@/components/SEO'
import { SponsorGate } from '@/components/crm/SponsorGate'
import { useLocaleContext } from '@/contexts/LocaleContext'
import { crmSupabase, getCrmDistributors, getCrmMembership } from '@/lib/crm'
import type { CrmDistributor, CrmMembership } from '@/lib/crm'
import type { Session } from '@supabase/supabase-js'
import { BarChart3, BookOpenCheck, ChevronRight, GitBranch, Languages, LayoutDashboard, LogOut, Megaphone, Settings2, Smartphone, Users } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

type Localized = Record<string, string>
type Course = { id:string; position:number; title:Localized; description:Localized; active:boolean }
type Module = { id:string; course_id:string|null; position:number; title:Localized; description:Localized; category:string; video_url:string|null; duration_minutes:number; passing_score:number }
type Progress = { distributor_id:string; module_id:string; completed:boolean }
type Relationship = { distributor_id:string; sponsor_distributor_id:string|null }
type EventRow = { distributor_id:string|null; event_name:string; campaign:string|null; occurred_at:string }
type ContentRow = { id:string; content_type:string; slug:string; title:Localized; published:boolean }
type Tab = 'academy'|'team'|'automation'|'analytics'|'admin'

const UI = {
  en:{ title:'True Legacy Platform', subtitle:'Learn, duplicate, lead, and measure—one connected system.', academy:'Academy', team:'Organization', automation:'Nurture', analytics:'Analytics', admin:'Content', back:'Lead dashboard', complete:'complete', lessons:'lessons', organization:'Your organization', direct:'Direct team', total:'Total organization', sponsor:'Sponsor', noSponsor:'Top-level leader', active:'Active nurture paths', automated:'Interest-based English, Spanish, and Portuguese follow-up paths are ready.', performance:'Performance overview', content:'Content control', mobile:'Installable mobile experience', mobileBody:'This platform is now prepared to install from the browser and use like an app.' },
  es:{ title:'Plataforma True Legacy', subtitle:'Aprende, duplica, lidera y mide—en un solo sistema.', academy:'Academia', team:'Organización', automation:'Nutrición', analytics:'Analíticas', admin:'Contenido', back:'Panel de prospectos', complete:'completado', lessons:'lecciones', organization:'Tu organización', direct:'Equipo directo', total:'Organización total', sponsor:'Patrocinador', noSponsor:'Líder de nivel superior', active:'Rutas activas', automated:'Las rutas de seguimiento por interés en inglés, español y portugués están listas.', performance:'Resumen de rendimiento', content:'Control de contenido', mobile:'Experiencia móvil instalable', mobileBody:'La plataforma está preparada para instalarse desde el navegador y usarse como una app.' },
  pt:{ title:'Plataforma True Legacy', subtitle:'Aprenda, duplique, lidere e meça—em um único sistema.', academy:'Academia', team:'Organização', automation:'Nutrição', analytics:'Análises', admin:'Conteúdo', back:'Painel de leads', complete:'concluído', lessons:'aulas', organization:'Sua organização', direct:'Equipe direta', total:'Organização total', sponsor:'Patrocinador', noSponsor:'Líder de nível superior', active:'Fluxos ativos', automated:'Os fluxos por interesse em inglês, espanhol e português estão prontos.', performance:'Visão de desempenho', content:'Controle de conteúdo', mobile:'Experiência móvel instalável', mobileBody:'A plataforma está pronta para ser instalada pelo navegador e usada como aplicativo.' },
} as const

export default function PhaseFourPage(){
  const { locale }=useLocaleContext(); const lang=locale==='es'?'es':locale==='pt'?'pt':'en'; const copy=UI[lang]
  const [session,setSession]=useState<Session|null>(null); const [membership,setMembership]=useState<CrmMembership|null>(null)
  const [tab,setTab]=useState<Tab>('academy'); const [courses,setCourses]=useState<Course[]>([]); const [modules,setModules]=useState<Module[]>([])
  const [progress,setProgress]=useState<Progress[]>([]); const [distributors,setDistributors]=useState<CrmDistributor[]>([]); const [relationships,setRelationships]=useState<Relationship[]>([])
  const [events,setEvents]=useState<EventRow[]>([]); const [content,setContent]=useState<ContentRow[]>([]); const [loading,setLoading]=useState(true)
  useEffect(()=>{crmSupabase?.auth.getSession().then(({data})=>setSession(data.session)); const {data}=crmSupabase!.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[])
  useEffect(()=>{if(!session||!crmSupabase)return;(async()=>{const member=await getCrmMembership(session.user.id);setMembership(member);if(!member?.active)return setLoading(false);const [cs,ms,ps,ds,rs,es,ct]=await Promise.all([crmSupabase.from('crm_courses').select('*').eq('active',true).order('position'),crmSupabase.from('crm_training_modules').select('*').eq('active',true).order('position'),crmSupabase.from('crm_training_progress').select('*'),getCrmDistributors(),crmSupabase.from('crm_team_relationships').select('*'),crmSupabase.from('crm_analytics_events').select('distributor_id,event_name,campaign,occurred_at').order('occurred_at',{ascending:false}).limit(2500),crmSupabase.from('crm_managed_content').select('id,content_type,slug,title,published').order('content_type')]);setCourses((cs.data||[]) as Course[]);setModules((ms.data||[]) as Module[]);setProgress((ps.data||[]) as Progress[]);setDistributors(ds);setRelationships((rs.data||[]) as Relationship[]);setEvents((es.data||[]) as EventRow[]);setContent((ct.data||[]) as ContentRow[]);setLoading(false)})().catch(()=>setLoading(false))},[session?.user.id])
  const me=membership?.distributor_id||''; const sponsorId=relationships.find(r=>r.distributor_id===me)?.sponsor_distributor_id||null
  const descendants=useMemo(()=>{const found=new Set<string>();let frontier=[me];while(frontier.length){const next=relationships.filter(r=>r.sponsor_distributor_id&&frontier.includes(r.sponsor_distributor_id)).map(r=>r.distributor_id).filter(id=>!found.has(id));next.forEach(id=>found.add(id));frontier=next}return found},[me,relationships])
  const visibleIds=membership?.role==='admin'?new Set(distributors.map(d=>d.id)):new Set([me,...descendants]); const direct=relationships.filter(r=>r.sponsor_distributor_id===me).length
  const eventRows=events.filter(e=>!e.distributor_id||visibleIds.has(e.distributor_id)); const done=progress.filter(p=>p.distributor_id===me&&p.completed).length
  if(!session)return <Gate title="Platform sign-in required" body="Sign in to the CRM to open Phase 4."/>
  if(loading)return <main className="min-h-screen bg-[#05091a]"/>
  if(!membership?.active)return <Gate title="Account not authorized" body="An active True Legacy profile is required."/>
  return <SponsorGate membership={membership} distributors={distributors}><main className="min-h-screen bg-[#05091a] px-3 pb-24 pt-5 text-white sm:px-6"><SEO title={`${copy.title} | True Legacy`} description={copy.subtitle} noIndex/><div className="mx-auto max-w-7xl"><header className="rounded-3xl border border-cyan-400/15 bg-[radial-gradient(circle_at_top_right,rgba(14,165,233,.18),transparent_35%),rgba(255,255,255,.03)] p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-cyan-300">Phase 4 · team application</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">{copy.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400 sm:text-base">{copy.subtitle}</p></div><div className="flex flex-wrap gap-2"><Link to="/crm" className="rounded-xl border border-white/10 px-4 py-3 text-sm">{copy.back}</Link><button onClick={()=>crmSupabase?.auth.signOut()} className="rounded-xl border border-white/10 p-3" aria-label="Sign out"><LogOut className="h-5 w-5"/></button></div></div></header>
  <nav className="sticky top-2 z-20 mt-5 grid grid-cols-5 gap-1 rounded-2xl border border-white/10 bg-[#091025]/95 p-1.5 shadow-2xl backdrop-blur">{([{id:'academy',label:copy.academy,icon:BookOpenCheck},{id:'team',label:copy.team,icon:GitBranch},{id:'automation',label:copy.automation,icon:Megaphone},{id:'analytics',label:copy.analytics,icon:BarChart3},{id:'admin',label:copy.admin,icon:Settings2}] as const).map(item=><button key={item.id} onClick={()=>setTab(item.id)} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl px-2 text-[10px] font-bold sm:flex-row sm:text-sm ${tab===item.id?'bg-cyan-500 text-slate-950':'text-slate-400 hover:bg-white/5'}`}><item.icon className="h-4 w-4"/>{item.label}</button>)}</nav>
  {tab==='academy'&&<section className="mt-6"><div className="grid gap-4 sm:grid-cols-3"><Metric value={`${done}/${modules.length}`} label={copy.complete}/><Metric value={courses.length} label={copy.academy}/><Metric value={modules.reduce((n,m)=>n+(m.duration_minutes||0),0)} label="minutes"/></div><div className="mt-6 space-y-5">{courses.map(course=>{const lessons=modules.filter(m=>m.course_id===course.id);const courseDone=lessons.filter(m=>progress.some(p=>p.distributor_id===me&&p.module_id===m.id&&p.completed)).length;return <article key={course.id} className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.03]"><div className="border-b border-white/10 p-5 sm:p-6"><div className="flex items-start justify-between gap-5"><div><h2 className="text-xl font-black">{course.title[lang]||course.title.en}</h2><p className="mt-2 text-sm text-slate-400">{course.description[lang]||course.description.en}</p></div><span className="whitespace-nowrap rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">{courseDone}/{lessons.length}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-to-r from-cyan-500 to-blue-500" style={{width:`${lessons.length?courseDone/lessons.length*100:0}%`}}/></div></div><div className="divide-y divide-white/10">{lessons.map(m=><a key={m.id} href={m.video_url||'#'} target={m.video_url?'_blank':undefined} rel="noreferrer" className="flex items-center gap-4 p-5 hover:bg-white/[.03]"><span className={`grid h-9 w-9 place-items-center rounded-full ${progress.some(p=>p.distributor_id===me&&p.module_id===m.id&&p.completed)?'bg-emerald-400/15 text-emerald-300':'bg-white/5 text-slate-500'}`}>{m.position}</span><div className="min-w-0 flex-1"><p className="truncate font-bold">{m.title[lang]||m.title.en}</p><p className="mt-1 text-xs text-slate-500">{m.duration_minutes||'—'} min · quiz {m.passing_score||80}%</p></div><ChevronRight className="h-4 w-4 text-slate-600"/></a>)}</div></article>})}</div></section>}
  {tab==='team'&&<section className="mt-6"><h2 className="text-2xl font-black">{copy.organization}</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Metric value={direct} label={copy.direct}/><Metric value={descendants.size} label={copy.total}/><Metric value={distributors.find(d=>d.id===sponsorId)?.display_name||copy.noSponsor} label={copy.sponsor}/></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{distributors.filter(d=>visibleIds.has(d.id)).map(d=><article key={d.id} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.03] p-4"><img src={d.avatar_url||'/logos/tl-square-white.png'} alt="" className="h-14 w-14 rounded-xl object-cover"/><div className="min-w-0"><p className="truncate font-bold">{d.display_name}</p><p className="truncate text-xs text-slate-500">{d.title}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-cyan-300">{relationships.find(r=>r.distributor_id===d.id)?.sponsor_distributor_id===me?'Direct team':'Organization'}</p></div></article>)}</div></section>}
  {tab==='automation'&&<section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-white/10 bg-white/[.03] p-6"><Megaphone className="h-8 w-8 text-cyan-300"/><h2 className="mt-5 text-2xl font-black">{copy.active}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{copy.automated}</p><div className="mt-6 grid gap-3">{['Product & Duo','Business opportunity','Training system','Live events'].map((x,i)=><div key={x} className="flex items-center justify-between rounded-xl border border-white/10 p-4"><span className="font-bold">{x}</span><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">{3+i%2} steps</span></div>)}</div></article><MobileCard copy={copy}/></section>}
  {tab==='analytics'&&<section className="mt-6"><h2 className="text-2xl font-black">{copy.performance}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric value={eventRows.filter(e=>e.event_name==='page_view'||e.event_name==='link_click').length} label="Link activity"/><Metric value={eventRows.filter(e=>e.event_name==='qr_open').length} label="QR opens"/><Metric value={eventRows.filter(e=>e.event_name==='lead').length} label="Leads"/><Metric value={eventRows.filter(e=>e.event_name==='conversion').length} label="Conversions"/></div><div className="mt-6 grid gap-4 lg:grid-cols-5">{['profile','business','duo','training','events'].map(c=>{const n=eventRows.filter(e=>e.campaign===c).length;return <div key={c} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="capitalize text-sm font-bold">{c}</p><p className="mt-3 text-3xl font-black text-cyan-300">{n}</p><p className="text-xs text-slate-500">tracked actions</p></div>})}</div></section>}
  {tab==='admin'&&<section className="mt-6"><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black">{copy.content}</h2><p className="mt-2 text-sm text-slate-500">Products, events, academy content, and announcements.</p></div>{membership.role==='admin'&&<span className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">Administrator</span>}</div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{['product','event','training','announcement'].map(type=><article key={type} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="capitalize font-black">{type}</p><p className="mt-3 text-3xl font-black text-cyan-300">{content.filter(c=>c.content_type===type).length}</p><p className="mt-1 text-xs text-slate-500">{content.filter(c=>c.content_type===type&&c.published).length} published</p></article>)}</div><div className="mt-6 rounded-2xl border border-amber-400/15 bg-amber-400/[.04] p-5 text-sm text-slate-300">The secure publishing model is ready. Administrator editing controls become active after the Phase 4 database update is applied.</div></section>}
  </div></main></SponsorGate>
}

function Metric({value,label}:{value:string|number;label:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-3xl font-black">{value}</p><p className="mt-1 text-xs uppercase tracking-wider text-slate-500">{label}</p></div>}
function MobileCard({copy}:{copy:(typeof UI)[keyof typeof UI]}){return <article className="rounded-3xl border border-white/10 bg-[linear-gradient(145deg,rgba(37,99,235,.16),rgba(255,255,255,.03))] p-6"><Smartphone className="h-8 w-8 text-blue-300"/><h2 className="mt-5 text-2xl font-black">{copy.mobile}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{copy.mobileBody}</p><div className="mt-6 flex items-center gap-3 rounded-2xl border border-white/10 p-4"><LayoutDashboard className="h-6 w-6 text-cyan-300"/><div><p className="font-bold">True Legacy</p><p className="text-xs text-slate-500">Mobile CRM & Academy</p></div></div><div className="mt-3 flex items-center gap-3 rounded-2xl border border-white/10 p-4"><Languages className="h-6 w-6 text-cyan-300"/><div><p className="font-bold">EN · ES · PT</p><p className="text-xs text-slate-500">Language-aware content tracks</p></div></div></article>}
function Gate({title,body}:{title:string;body:string}){return <main className="grid min-h-screen place-items-center bg-[#05091a] px-4 text-white"><div className="max-w-md rounded-3xl border border-cyan-400/20 bg-white/[.03] p-8 text-center"><Users className="mx-auto h-10 w-10 text-cyan-300"/><h1 className="mt-5 text-3xl font-black">{title}</h1><p className="mt-3 text-sm text-slate-400">{body}</p><Link to="/crm" className="mt-6 inline-flex rounded-xl bg-cyan-500 px-5 py-3 font-bold text-slate-950">Open CRM</Link></div></main>}
