import { SEO } from '@/components/SEO'
import { SponsorGate } from '@/components/crm/SponsorGate'
import { useLocaleContext } from '@/contexts/LocaleContext'
import { crmSupabase, getCrmDistributors, getCrmMembership } from '@/lib/crm'
import type { CrmDistributor, CrmMembership } from '@/lib/crm'
import type { Session } from '@supabase/supabase-js'
import { BarChart3, BookOpenCheck, CheckCircle2, ChevronRight, GitBranch, Languages, LayoutDashboard, LogOut, Megaphone, Pencil, Settings2, Smartphone, Users, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

type Localized = Record<string, string>
type Course = { id:string; position:number; title:Localized; description:Localized; active:boolean }
type Module = { id:string; course_id:string|null; position:number; title:Localized; description:Localized; category:string; video_url:string|null; duration_minutes:number; passing_score:number }
type Progress = { distributor_id:string; module_id:string; completed:boolean }
type Relationship = { distributor_id:string; sponsor_distributor_id:string|null }
type EventRow = { distributor_id:string|null; event_name:string; campaign:string|null; occurred_at:string }
type ContentRow = { id:string; content_type:string; slug:string; title:Localized; published:boolean }
type QuizQuestion = { id:string; module_id:string; position:number; prompt:Localized; choices:Record<string,string[]> }
type Campaign = { id:string; interest:string; locale:string; name:string; steps:Array<{delay_hours:number;channel:string;campaign?:string;subject?:string}>; active:boolean }
type Tab = 'academy'|'team'|'automation'|'analytics'|'admin'

const UI = {
  en:{ title:'True Legacy Platform', subtitle:'Learn, duplicate, lead, and measure—one connected system.', academy:'Academy', team:'Organization', automation:'Nurture', analytics:'Analytics', admin:'Content', back:'Lead dashboard', complete:'complete', lessons:'lessons', organization:'Your organization', direct:'Direct team', total:'Total organization', sponsor:'Sponsor', noSponsor:'Top-level leader', active:'Active nurture paths', automated:'Interest-based English, Spanish, and Portuguese follow-up paths are ready.', performance:'Performance overview', content:'Content control', mobile:'Installable mobile experience', mobileBody:'This platform is now prepared to install from the browser and use like an app.' },
  es:{ title:'Plataforma True Legacy', subtitle:'Aprende, duplica, lidera y mide—en un solo sistema.', academy:'Academia', team:'Organización', automation:'Nutrición', analytics:'Analíticas', admin:'Contenido', back:'Panel de prospectos', complete:'completado', lessons:'lecciones', organization:'Tu organización', direct:'Equipo directo', total:'Organización total', sponsor:'Patrocinador', noSponsor:'Líder de nivel superior', active:'Rutas activas', automated:'Las rutas de seguimiento por interés en inglés, español y portugués están listas.', performance:'Resumen de rendimiento', content:'Control de contenido', mobile:'Experiencia móvil instalable', mobileBody:'La plataforma está preparada para instalarse desde el navegador y usarse como una app.' },
  pt:{ title:'Plataforma True Legacy', subtitle:'Aprenda, duplique, lidere e meça—em um único sistema.', academy:'Academia', team:'Organização', automation:'Nutrição', analytics:'Análises', admin:'Conteúdo', back:'Painel de leads', complete:'concluído', lessons:'aulas', organization:'Sua organização', direct:'Equipe direta', total:'Organização total', sponsor:'Patrocinador', noSponsor:'Líder de nível superior', active:'Fluxos ativos', automated:'Os fluxos por interesse em inglês, espanhol e português estão prontos.', performance:'Visão de desempenho', content:'Controle de conteúdo', mobile:'Experiência móvel instalável', mobileBody:'A plataforma está pronta para ser instalada pelo navegador e usada como aplicativo.' },
} as const

export default function PhaseFourPage(){
  const { locale }=useLocaleContext(); const lang=locale==='es'?'es':locale==='pt'?'pt':'en'; const copy=UI[lang]
  const [session,setSession]=useState<Session|null>(null); const [membership,setMembership]=useState<CrmMembership|null>(null)
  const [tab,setTab]=useState<Tab>('academy'); const [courses,setCourses]=useState<Course[]>([]); const [modules,setModules]=useState<Module[]>([])
  const [progress,setProgress]=useState<Progress[]>([]); const [distributors,setDistributors]=useState<CrmDistributor[]>([]); const [relationships,setRelationships]=useState<Relationship[]>([])
  const [events,setEvents]=useState<EventRow[]>([]); const [content,setContent]=useState<ContentRow[]>([]); const [loading,setLoading]=useState(true)
  const [questions,setQuestions]=useState<QuizQuestion[]>([]); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [selectedModule,setSelectedModule]=useState<Module|null>(null)
  const [answers,setAnswers]=useState<Record<number,number>>({}); const [quizResult,setQuizResult]=useState<{score:number;passed:boolean}|null>(null); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState('')
  useEffect(()=>{crmSupabase?.auth.getSession().then(({data})=>setSession(data.session)); const {data}=crmSupabase!.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[])
  useEffect(()=>{if(!session||!crmSupabase)return;(async()=>{const member=await getCrmMembership(session.user.id);setMembership(member);if(!member?.active)return setLoading(false);const [cs,ms,ps,ds,rs,es,ct,qs,nc]=await Promise.all([crmSupabase.from('crm_courses').select('*').eq('active',true).order('position'),crmSupabase.from('crm_training_modules').select('*').eq('active',true).order('position'),crmSupabase.from('crm_training_progress').select('*'),getCrmDistributors(),crmSupabase.from('crm_team_relationships').select('*'),crmSupabase.from('crm_analytics_events').select('distributor_id,event_name,campaign,occurred_at').order('occurred_at',{ascending:false}).limit(2500),crmSupabase.from('crm_managed_content').select('id,content_type,slug,title,published').order('content_type'),crmSupabase.from('crm_quiz_questions').select('id,module_id,position,prompt,choices').eq('active',true).order('position'),crmSupabase.from('crm_nurture_campaigns').select('*').eq('active',true).order('interest')]);setCourses((cs.data||[]) as Course[]);setModules((ms.data||[]) as Module[]);setProgress((ps.data||[]) as Progress[]);setDistributors(ds);setRelationships((rs.data||[]) as Relationship[]);setEvents((es.data||[]) as EventRow[]);setContent((ct.data||[]) as ContentRow[]);setQuestions((qs.data||[]) as QuizQuestion[]);setCampaigns((nc.data||[]) as Campaign[]);setLoading(false)})().catch(()=>setLoading(false))},[session?.user.id])
  const me=membership?.distributor_id||''; const sponsorId=relationships.find(r=>r.distributor_id===me)?.sponsor_distributor_id||null
  const descendants=useMemo(()=>{const found=new Set<string>();let frontier=[me];while(frontier.length){const next=relationships.filter(r=>r.sponsor_distributor_id&&frontier.includes(r.sponsor_distributor_id)).map(r=>r.distributor_id).filter(id=>!found.has(id));next.forEach(id=>found.add(id));frontier=next}return found},[me,relationships])
  const visibleIds=membership?.role==='admin'?new Set(distributors.map(d=>d.id)):new Set([me,...descendants]); const direct=relationships.filter(r=>r.sponsor_distributor_id===me).length
  const eventRows=events.filter(e=>!e.distributor_id||visibleIds.has(e.distributor_id)); const done=progress.filter(p=>p.distributor_id===me&&p.completed).length
  const markComplete=async(module:Module)=>{if(!crmSupabase||!me)return;setSaving(true);setNotice('');const {error}=await crmSupabase.rpc('crm_set_training_progress',{p_distributor_id:me,p_module_id:module.id,p_completed:true});if(error)setNotice(error.message);else{setProgress(current=>[...current.filter(p=>!(p.distributor_id===me&&p.module_id===module.id)),{distributor_id:me,module_id:module.id,completed:true}]);setNotice('Lesson completed and progress saved.')}setSaving(false)}
  const submitQuiz=async()=>{if(!crmSupabase||!selectedModule)return;setSaving(true);setNotice('');const {data,error}=await crmSupabase.rpc('crm_submit_quiz',{p_module_id:selectedModule.id,p_answers:answers});if(error)setNotice(error.message);else{const result=(Array.isArray(data)?data[0]:data) as {score:number;passed:boolean};setQuizResult(result);if(result.passed)await markComplete(selectedModule)}setSaving(false)}
  const toggleContent=async(row:ContentRow)=>{if(!crmSupabase||membership?.role!=='admin')return;const next=!row.published;const {error}=await crmSupabase.from('crm_managed_content').update({published:next}).eq('id',row.id);if(!error)setContent(current=>current.map(item=>item.id===row.id?{...item,published:next}:item))}
  const openModule=(module:Module)=>{setSelectedModule(module);setAnswers({});setQuizResult(null);setNotice('')}
  if(!session)return <Gate title="Platform sign-in required" body="Sign in to the CRM to open Phase 4."/>
  if(loading)return <main className="min-h-screen bg-black"/>
  if(!membership?.active)return <Gate title="Account not authorized" body="An active True Legacy profile is required."/>
  return <SponsorGate membership={membership} distributors={distributors}><main className="min-h-screen bg-black px-3 pb-24 pt-5 text-white sm:px-6"><SEO title={`${copy.title} | True Legacy`} description={copy.subtitle} noIndex/><div className="mx-auto max-w-7xl"><header className="rounded-3xl border border-white/20 bg-[radial-gradient(circle_at_top_right,rgba(14,165,233,.18),transparent_35%),rgba(255,255,255,.03)] p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-[#2997ff]">Phase 4 · team application</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">{copy.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#cccccc] sm:text-base">{copy.subtitle}</p></div><div className="flex flex-wrap gap-2"><Link to="/crm" className="rounded-xl border border-white/10 px-4 py-3 text-sm">{copy.back}</Link><button onClick={()=>crmSupabase?.auth.signOut()} className="rounded-xl border border-white/10 p-3" aria-label="Sign out"><LogOut className="h-5 w-5"/></button></div></div></header>
  <nav className="sticky top-2 z-20 mt-5 flex items-center gap-1.5 overflow-x-auto rounded-2xl border border-white/10 bg-black/95 p-1.5 shadow-2xl backdrop-blur [scrollbar-width:none] [-ms-overflow-style:none] [&::-webkit-scrollbar]:hidden">
    {(
      [
        { id: 'academy', label: copy.academy, icon: BookOpenCheck },
        { id: 'team', label: copy.team, icon: GitBranch },
        { id: 'automation', label: copy.automation, icon: Megaphone },
        { id: 'analytics', label: copy.analytics, icon: BarChart3 },
        { id: 'admin', label: copy.admin, icon: Settings2 },
      ] as const
    ).map((item) => (
      <button
        key={item.id}
        type="button"
        onClick={() => setTab(item.id)}
        className={`flex min-h-11 shrink-0 sm:flex-1 items-center justify-center gap-1.5 rounded-xl px-3.5 text-xs font-bold whitespace-nowrap transition-all ${
          tab === item.id ? 'bg-cyan-500 text-slate-950 shadow-md' : 'text-[#cccccc] hover:bg-white/5'
        }`}
      >
        <item.icon className="h-4 w-4 shrink-0" />
        <span className="whitespace-nowrap inline-block">{item.label}</span>
      </button>
    ))}
  </nav>
  {tab==='academy'&&<section className="mt-6"><div className="grid gap-4 sm:grid-cols-3"><Metric value={`${done}/${modules.length}`} label={copy.complete}/><Metric value={courses.length} label={copy.academy}/><Metric value={modules.reduce((n,m)=>n+(m.duration_minutes||0),0)} label="minutes"/></div><div className="mt-6 space-y-5">{courses.map(course=>{const lessons=modules.filter(m=>m.course_id===course.id);const courseDone=lessons.filter(m=>progress.some(p=>p.distributor_id===me&&p.module_id===m.id&&p.completed)).length;return <article key={course.id} className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.03]"><div className="border-b border-white/10 p-5 sm:p-6"><div className="flex items-start justify-between gap-5"><div><h2 className="text-xl font-black">{course.title[lang]||course.title.en}</h2><p className="mt-2 text-sm text-[#cccccc]">{course.description[lang]||course.description.en}</p></div><span className="whitespace-nowrap rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-[#2997ff]">{courseDone}/{lessons.length}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-to-r from-cyan-500 to-blue-500" style={{width:`${lessons.length?courseDone/lessons.length*100:0}%`}}/></div></div><div className="divide-y divide-white/10">{lessons.map(m=><button key={m.id} onClick={()=>openModule(m)} className="flex w-full items-center gap-4 p-5 text-left hover:bg-white/[.03]"><span className={`grid h-9 w-9 place-items-center rounded-full ${progress.some(p=>p.distributor_id===me&&p.module_id===m.id&&p.completed)?'bg-emerald-400/15 text-[#cccccc]':'bg-white/5 text-[#86868b]'}`}>{progress.some(p=>p.distributor_id===me&&p.module_id===m.id&&p.completed)?<CheckCircle2 className="h-5 w-5"/>:m.position}</span><div className="min-w-0 flex-1"><p className="truncate font-bold">{m.title[lang]||m.title.en}</p><p className="mt-1 text-xs text-[#86868b]">{m.duration_minutes||'—'} min · {questions.some(q=>q.module_id===m.id)?`quiz ${m.passing_score||80}%`:'completion check'}</p></div><ChevronRight className="h-4 w-4 text-[#86868b]"/></button>)}</div></article>})}</div></section>}
  {tab==='team'&&<section className="mt-6"><h2 className="text-2xl font-black">{copy.organization}</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Metric value={direct} label={copy.direct}/><Metric value={descendants.size} label={copy.total}/><Metric value={distributors.find(d=>d.id===sponsorId)?.display_name||copy.noSponsor} label={copy.sponsor}/></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{distributors.filter(d=>visibleIds.has(d.id)).map(d=><article key={d.id} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.03] p-4"><img src={d.avatar_url||'/logos/tl-square-white.png'} alt="" className="h-14 w-14 rounded-xl object-cover"/><div className="min-w-0"><p className="truncate font-bold">{d.display_name}</p><p className="truncate text-xs text-[#86868b]">{d.title}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-[#2997ff]">{relationships.find(r=>r.distributor_id===d.id)?.sponsor_distributor_id===me?'Direct team':'Organization'}</p></div></article>)}</div></section>}
  {tab==='automation'&&<section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-white/10 bg-white/[.03] p-6"><Megaphone className="h-8 w-8 text-[#2997ff]"/><h2 className="mt-5 text-2xl font-black">{copy.active}</h2><p className="mt-3 text-sm leading-6 text-[#cccccc]">{copy.automated}</p><div className="mt-6 grid gap-3">{campaigns.filter(c=>c.locale===lang).map(c=><div key={c.id} className="rounded-xl border border-white/10 p-4"><div className="flex items-center justify-between"><span className="font-bold capitalize">{c.interest}</span><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-[#cccccc]">{c.steps.length} steps</span></div><div className="mt-3 flex flex-wrap gap-2">{c.steps.map((step,i)=><span key={i} className="rounded-lg bg-white/5 px-2.5 py-1 text-[11px] text-[#cccccc]">{i+1}. {step.channel} · {step.delay_hours===0?'now':`${step.delay_hours}h`}</span>)}</div></div>)}</div></article><MobileCard copy={copy}/></section>}
  {tab==='analytics'&&<section className="mt-6"><h2 className="text-2xl font-black">{copy.performance}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric value={eventRows.filter(e=>e.event_name==='page_view'||e.event_name==='link_click').length} label="Link activity"/><Metric value={eventRows.filter(e=>e.event_name==='qr_open').length} label="QR opens"/><Metric value={eventRows.filter(e=>e.event_name==='lead').length} label="Leads"/><Metric value={eventRows.filter(e=>e.event_name==='conversion').length} label="Conversions"/></div><div className="mt-6 grid gap-4 lg:grid-cols-5">{['profile','business','duo','training','events'].map(c=>{const n=eventRows.filter(e=>e.campaign===c).length;return <div key={c} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="capitalize text-sm font-bold">{c}</p><p className="mt-3 text-3xl font-black text-[#2997ff]">{n}</p><p className="text-xs text-[#86868b]">tracked actions</p></div>})}</div></section>}
  {tab==='admin'&&<section className="mt-6"><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black">{copy.content}</h2><p className="mt-2 text-sm text-[#86868b]">Products, events, academy content, and announcements.</p></div>{membership.role==='admin'&&<span className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-[#2997ff]">Administrator</span>}</div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{['product','event','training','announcement'].map(type=><article key={type} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="capitalize font-black">{type}</p><p className="mt-3 text-3xl font-black text-[#2997ff]">{content.filter(c=>c.content_type===type).length}</p><p className="mt-1 text-xs text-[#86868b]">{content.filter(c=>c.content_type===type&&c.published).length} published</p></article>)}</div><div className="mt-6 overflow-hidden rounded-2xl border border-white/10">{content.length===0?<p className="p-5 text-sm text-[#86868b]">No managed content has been added yet.</p>:content.map(row=><div key={row.id} className="flex items-center gap-4 border-b border-white/10 p-4 last:border-0"><div className="min-w-0 flex-1"><p className="truncate font-bold">{row.title[lang]||row.title.en||row.slug}</p><p className="text-xs capitalize text-[#86868b]">{row.content_type} · {row.slug}</p></div><button disabled={membership.role!=='admin'} onClick={()=>toggleContent(row)} className={`rounded-full px-3 py-1 text-xs font-bold ${row.published?'bg-emerald-400/10 text-[#cccccc]':'bg-white/5 text-[#86868b]'} disabled:cursor-not-allowed`}>{row.published?'Published':'Draft'}</button>{membership.role==='admin'&&<Pencil className="h-4 w-4 text-[#86868b]"/>}</div>)}</div>{membership.role!=='admin'&&<div className="mt-6 rounded-2xl border border-amber-400/15 bg-amber-400/[.04] p-5 text-sm text-[#cccccc]">Content editing is limited to True Legacy administrators.</div>}</section>}
  </div>{selectedModule&&<LessonModal module={selectedModule} lang={lang} questions={questions.filter(q=>q.module_id===selectedModule.id)} answers={answers} setAnswers={setAnswers} result={quizResult} saving={saving} notice={notice} completed={progress.some(p=>p.distributor_id===me&&p.module_id===selectedModule.id&&p.completed)} close={()=>setSelectedModule(null)} complete={()=>markComplete(selectedModule)} submitQuiz={submitQuiz}/>}</main></SponsorGate>
}

function LessonModal({module,lang,questions,answers,setAnswers,result,saving,notice,completed,close,complete,submitQuiz}:{module:Module;lang:string;questions:QuizQuestion[];answers:Record<number,number>;setAnswers:(value:Record<number,number>)=>void;result:{score:number;passed:boolean}|null;saving:boolean;notice:string;completed:boolean;close:()=>void;complete:()=>void;submitQuiz:()=>void}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/90 p-3 backdrop-blur sm:p-8"><div className="mx-auto max-w-3xl rounded-3xl border border-white/10 bg-black p-5 shadow-2xl sm:p-8"><div className="flex items-start gap-5"><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#2997ff]">Academy lesson</p><h2 className="mt-2 text-2xl font-black">{module.title[lang]||module.title.en}</h2><p className="mt-3 text-sm leading-6 text-[#cccccc]">{module.description[lang]||module.description.en}</p></div><button onClick={close} className="rounded-xl border border-white/10 p-2" aria-label="Close lesson"><X className="h-5 w-5"/></button></div>{module.video_url&&<div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-black"><iframe className="aspect-video w-full" src={toEmbed(module.video_url)} title={module.title.en} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div>}{questions.length>0&&<div className="mt-7 space-y-5">{questions.map(q=><fieldset key={q.id} className="rounded-2xl border border-white/10 p-5"><legend className="px-2 font-bold">{q.prompt[lang]||q.prompt.en}</legend><div className="mt-3 grid gap-2">{(q.choices[lang]||q.choices.en||[]).map((choice,index)=><label key={choice} className={`flex cursor-pointer gap-3 rounded-xl border p-3 text-sm ${answers[q.position]===index?'border-white/20 bg-cyan-400/10':'border-white/10'}`}><input type="radio" name={q.id} checked={answers[q.position]===index} onChange={()=>setAnswers({...answers,[q.position]:index})}/>{choice}</label>)}</div></fieldset>)}</div>}{result&&<div className={`mt-6 rounded-2xl p-4 ${result.passed?'bg-emerald-400/10 text-[#cccccc]':'bg-amber-400/10 text-amber-100'}`}>Score: {result.score}% · {result.passed?'Passed':'Review the lesson and try again'}</div>}{notice&&<p className="mt-4 text-sm text-[#2997ff]">{notice}</p>}<div className="mt-7 flex flex-wrap justify-end gap-3">{questions.length?<button disabled={saving||questions.some(q=>answers[q.position]===undefined)} onClick={submitQuiz} className="rounded-xl bg-cyan-500 px-5 py-3 font-bold text-slate-950 disabled:opacity-40">Submit quiz</button>:<button disabled={saving||completed} onClick={complete} className="rounded-xl bg-cyan-500 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">{completed?'Completed':'Mark lesson complete'}</button>}</div></div></div>}

function toEmbed(url:string){const match=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/))([\w-]+)/);return match?`https://www.youtube.com/embed/${match[1]}`:url}

function Metric({value,label}:{value:string|number;label:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-3xl font-black">{value}</p><p className="mt-1 text-xs uppercase tracking-wider text-[#86868b]">{label}</p></div>}
function MobileCard({copy}:{copy:(typeof UI)[keyof typeof UI]}){return <article className="rounded-3xl border border-white/10 bg-[linear-gradient(145deg,rgba(37,99,235,.16),rgba(255,255,255,.03))] p-6"><Smartphone className="h-8 w-8 text-blue-300"/><h2 className="mt-5 text-2xl font-black">{copy.mobile}</h2><p className="mt-3 text-sm leading-6 text-[#cccccc]">{copy.mobileBody}</p><div className="mt-6 flex items-center gap-3 rounded-2xl border border-white/10 p-4"><LayoutDashboard className="h-6 w-6 text-[#2997ff]"/><div><p className="font-bold">True Legacy</p><p className="text-xs text-[#86868b]">Mobile CRM & Academy</p></div></div><div className="mt-3 flex items-center gap-3 rounded-2xl border border-white/10 p-4"><Languages className="h-6 w-6 text-[#2997ff]"/><div><p className="font-bold">EN · ES · PT</p><p className="text-xs text-[#86868b]">Language-aware content tracks</p></div></div></article>}
function Gate({title,body}:{title:string;body:string}){return <main className="grid min-h-screen place-items-center bg-black px-4 text-white"><div className="max-w-md rounded-3xl border border-white/20 bg-white/[.03] p-8 text-center"><Users className="mx-auto h-10 w-10 text-[#2997ff]"/><h1 className="mt-5 text-3xl font-black">{title}</h1><p className="mt-3 text-sm text-[#cccccc]">{body}</p><Link to="/crm" className="mt-6 inline-flex rounded-xl bg-cyan-500 px-5 py-3 font-bold text-slate-950">Open CRM</Link></div></main>}
